import type { ApiResponse, PagedFilter } from '@/types/api';
export interface DefinitionItem{id:number;code:string;name:string;isDefault:boolean}
export interface ProductDefinitions{categories:DefinitionItem[];groups:DefinitionItem[];brands:DefinitionItem[];unitCategories:DefinitionItem[];units:DefinitionItem[];packageTypes:DefinitionItem[];taxGroups:DefinitionItem[]}
export interface ProductListItem{id:number;code:string;name:string;category:string;group:string;brand?:string|null;baseUnit:string;productType:number;trackingType:number;lifecycleStatus:number;isActive:boolean}
export interface PagedResult<T>{items:T[];pageNumber:number;pageSize:number;totalCount:number;totalPages:number;hasPreviousPage:boolean;hasNextPage:boolean}
export interface ProductListQuery{pageNumber:number;pageSize:number;search?:string;sortBy?:string;sortDirection?:'asc'|'desc';filters?:PagedFilter[];filterLogic?:'and'|'or'}
export type ProductListResponse=ApiResponse<PagedResult<ProductListItem>>;
export interface SaveProductRequest{code:string;name:string;searchName?:string;description?:string;productType:number;lifecycleStatus:number;trackingType:number;valuationMethod:number;procurementType:number;productCategoryId:number;productGroupId:number;brandId?:number|null;baseUnitId:number;purchaseTaxGroupId:number;salesTaxGroupId:number;countryOfOriginCode?:string;customsTariffCode?:string;manufacturerCode?:string;netWeight?:number|null;grossWeight?:number|null;volume?:number|null;shelfLifeDays?:number|null;isPurchasable:boolean;isSellable:boolean;isInventoryTracked:boolean;units:unknown[];barcodes:unknown[];branchSettings:unknown[];translations:unknown[]}
export type ProductDefinitionKind='categories'|'groups'|'brands'|'unit-categories'|'units'|'package-types';
export interface ManagedProductDefinition extends DefinitionItem{description?:string|null;isActive:boolean;displayOrder:number;parentId?:number|null;website?:string|null;unitCategoryId?:number|null;symbol?:string|null;decimalPlaces?:number|null;conversionFactor?:number|null;isBaseUnit?:boolean|null;roundingMethod?:number|null;length?:number|null;width?:number|null;height?:number|null;emptyWeight?:number|null;dimensionUnitId?:number|null;weightUnitId?:number|null}
export interface SaveProductDefinitionRequest{code:string;name:string;description?:string;isActive:boolean;isDefault:boolean;displayOrder:number;parentId?:number|null;website?:string;unitCategoryId?:number|null;symbol?:string;decimalPlaces?:number|null;conversionFactor?:number|null;isBaseUnit?:boolean|null;roundingMethod?:number|null;length?:number|null;width?:number|null;height?:number|null;emptyWeight?:number|null;dimensionUnitId?:number|null;weightUnitId?:number|null}
