import { useEffect, useState, type FormEvent, type ReactElement } from 'react';
import { useQuery } from '@tanstack/react-query';
import { ArrowLeft, Pencil, Plus, Trash2 } from 'lucide-react';
import { useNavigate, useSearchParams } from 'react-router-dom';
import { toast } from 'sonner';
import { Button } from '@/components/ui/button';
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { businessPartnerApi } from '../api/business-partner-api';
import type { DefinitionKind, ManagedDefinition, SaveDefinitionRequest } from '../types/business-partner.types';

const kinds:{key:DefinitionKind;label:string;description:string}[]=[
  {key:'partner-types',label:'Cari Tipleri',description:'Müşteri, tedarikçi ve aday gibi cari rolleri'},
  {key:'customer-groups',label:'Cari Grupları',description:'Segmentasyon ve raporlama grupları'},
  {key:'payment-terms',label:'Ödeme Koşulları',description:'Vade ve erken ödeme koşulları'},
  {key:'currencies',label:'Para Birimleri',description:'ISO kodu, sembol ve ondalık hassasiyeti'},
  {key:'tax-groups',label:'Vergi Grupları',description:'Yurt içi, ihracat ve istisna tanımları'},
];

export function BusinessPartnerDefinitionsPage({fixedKind}:{fixedKind?:DefinitionKind}={}):ReactElement{
  const navigate=useNavigate(); const [searchParams,setSearchParams]=useSearchParams(); const requestedKind=fixedKind??searchParams.get('type') as DefinitionKind|null; const initialKind=kinds.some(x=>x.key===requestedKind)?requestedKind!:'partner-types'; const [kind,setKindState]=useState<DefinitionKind>(initialKind); const [pageNumber,setPageNumber]=useState(1); const [pageSize,setPageSize]=useState(20); const [search,setSearch]=useState(''); const [editing,setEditing]=useState<ManagedDefinition|null>(null); const [formOpen,setFormOpen]=useState(false); const [saving,setSaving]=useState(false);
  const setKind=(next:DefinitionKind)=>{setKindState(next);setPageNumber(1);if(fixedKind)navigate(`/accounts/definitions/${next}`);else setSearchParams({type:next});};
  useEffect(()=>{if(requestedKind&&kinds.some(x=>x.key===requestedKind)&&requestedKind!==kind){setKindState(requestedKind);setPageNumber(1);}},[kind,requestedKind]);
  const query=useQuery({queryKey:['managed-business-partner-definitions',kind,pageNumber,pageSize,search],queryFn:()=>businessPartnerApi.getManagedDefinitions(kind,{pageNumber,pageSize,search,sortBy:'displayOrder',sortDirection:'asc'})}); const page=query.data?.data; const rows=page?.items??[]; const current=kinds.find(x=>x.key===kind)!;
  const openCreate=()=>{setEditing(null);setFormOpen(true)}; const openEdit=(row:ManagedDefinition)=>{setEditing(row);setFormOpen(true)};
  const submit=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const f=new FormData(event.currentTarget);const nullableNumber=(key:string)=>{const v=String(f.get(key)??'').trim();return v===''?null:Number(v)};const payload:SaveDefinitionRequest={code:String(f.get('code')??''),name:String(f.get('name')??''),description:String(f.get('description')??''),isActive:f.get('isActive')==='on',isDefault:f.get('isDefault')==='on',displayOrder:Number(f.get('displayOrder')??0),dueDays:nullableNumber('dueDays'),discountDays:nullableNumber('discountDays'),discountRate:nullableNumber('discountRate'),isoCode:String(f.get('isoCode')??''),symbol:String(f.get('symbol')??''),decimalPlaces:nullableNumber('decimalPlaces'),isTaxExempt:f.get('isTaxExempt')==='on'};try{setSaving(true);if(editing)await businessPartnerApi.updateDefinition(kind,editing.id,payload);else await businessPartnerApi.createDefinition(kind,payload);toast.success('Tanım kaydedildi.');setFormOpen(false);await query.refetch();}catch(error){toast.error(error instanceof Error?error.message:'Tanım kaydedilemedi.');}finally{setSaving(false)}};
  const deactivate=async(row:ManagedDefinition)=>{if(!window.confirm(`${row.name} tanımını pasifleştirmek istiyor musunuz?`))return;try{await businessPartnerApi.deleteDefinition(kind,row.id);toast.success('Tanım pasifleştirildi.');await query.refetch();}catch(error){toast.error(error instanceof Error?error.message:'İşlem başarısız.')}};
  return <div className="space-y-5"><div className="flex flex-col justify-between gap-4 rounded-3xl bg-gradient-to-br from-violet-950 to-indigo-950 p-6 text-white md:flex-row md:items-end"><div><button type="button" onClick={()=>navigate('/accounts')} className="mb-4 inline-flex items-center gap-2 text-sm text-violet-200 hover:text-white"><ArrowLeft className="h-4 w-4"/>Cari listesine dön</button><h1 className="text-3xl font-semibold">Cari Tanımları</h1><p className="mt-2 text-slate-300">Cari kartında kullanılan bütün parametrik tanımları yönetin.</p></div><Button onClick={openCreate}><Plus/>Yeni Tanım</Button></div>
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{kinds.map(item=><button key={item.key} type="button" onClick={()=>setKind(item.key)} className={`rounded-2xl border p-4 text-start transition ${kind===item.key?'border-violet-500 bg-violet-50 ring-2 ring-violet-500/20 dark:bg-violet-500/10':'bg-card hover:border-violet-300'}`}><div className="font-semibold">{item.label}</div><div className="mt-1 text-xs text-muted-foreground">{item.description}</div></button>)}</div>
    <section className="overflow-hidden rounded-2xl border bg-card"><div className="flex flex-col justify-between gap-4 border-b p-5 sm:flex-row sm:items-center"><div><h2 className="text-lg font-semibold">{current.label}</h2><p className="text-sm text-muted-foreground">{current.description}</p></div><div className="flex gap-2"><Input value={search} onChange={event=>{setSearch(event.target.value);setPageNumber(1)}} placeholder="Kod, ad veya açıklama ara..." className="w-64"/><Button onClick={openCreate}><Plus/>Ekle</Button></div></div><div className="overflow-x-auto"><table className="w-full min-w-[860px] text-sm"><thead className="bg-muted/50 text-start"><tr><th className="p-4 text-start">Kayıt ID</th><th className="p-4 text-start">Kod</th><th className="p-4 text-start">Ad</th><th className="p-4 text-start">Açıklama</th><th className="p-4">Sıra</th><th className="p-4">Varsayılan</th><th className="p-4">Durum</th><th className="p-4 text-end">İşlemler</th></tr></thead><tbody>{rows.map(row=><tr key={row.id} className="border-t"><td className="p-4 font-mono font-semibold">#{row.id}</td><td className="p-4 font-mono font-semibold text-violet-700">{row.code}</td><td className="p-4 font-medium">{row.name}</td><td className="p-4 text-muted-foreground">{row.description||'—'}</td><td className="p-4 text-center">{row.displayOrder}</td><td className="p-4 text-center">{row.isDefault?'Evet':'—'}</td><td className="p-4 text-center"><span className={row.isActive?'text-emerald-600':'text-slate-400'}>{row.isActive?'Aktif':'Pasif'}</span></td><td className="p-4"><div className="flex justify-end gap-2"><Button size="icon-sm" variant="outline" aria-label="Düzenle" onClick={()=>openEdit(row)}><Pencil/></Button><Button size="icon-sm" variant="outline" aria-label="Pasifleştir" disabled={row.isDefault||!row.isActive} onClick={()=>void deactivate(row)}><Trash2/></Button></div></td></tr>)}{!query.isLoading&&rows.length===0?<tr><td colSpan={8} className="p-10 text-center text-muted-foreground">Kayıt bulunamadı.</td></tr>:null}</tbody></table></div><div className="flex flex-col items-center justify-between gap-3 border-t p-4 sm:flex-row"><div className="flex items-center gap-2 text-sm text-muted-foreground"><select value={pageSize} onChange={event=>{setPageSize(Number(event.target.value));setPageNumber(1)}} className="h-9 rounded-md border bg-background px-2"><option value={10}>10</option><option value={20}>20</option><option value={50}>50</option><option value={100}>100</option></select><span>{page?.totalCount??0} kayıt · Sayfa {page?.pageNumber??1} / {page?.totalPages??0}</span></div><div className="flex gap-2"><Button variant="outline" disabled={!page?.hasPreviousPage||query.isFetching} onClick={()=>setPageNumber(value=>Math.max(1,value-1))}>Önceki</Button><Button variant="outline" disabled={!page?.hasNextPage||query.isFetching} onClick={()=>setPageNumber(value=>value+1)}>Sonraki</Button></div></div></section>
    <DefinitionDialog key={`${kind}-${editing?.id??'new'}`} open={formOpen} onOpenChange={setFormOpen} kind={kind} item={editing} saving={saving} onSubmit={submit}/>
  </div>;
}

function DefinitionDialog({open,onOpenChange,kind,item,saving,onSubmit}:{open:boolean;onOpenChange:(v:boolean)=>void;kind:DefinitionKind;item:ManagedDefinition|null;saving:boolean;onSubmit:(e:FormEvent<HTMLFormElement>)=>void}):ReactElement{return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="lg:max-w-2xl"><DialogHeader><DialogTitle>{item?'Tanımı Düzenle':'Yeni Tanım'}</DialogTitle><DialogDescription>{kinds.find(x=>x.key===kind)?.label}</DialogDescription></DialogHeader><form onSubmit={onSubmit} className="space-y-5"><div className="grid gap-4 sm:grid-cols-2"><Field label="Kod"><Input name="code" required defaultValue={item?.code}/></Field><Field label="Ad"><Input name="name" required defaultValue={item?.name}/></Field><Field label="Sıralama"><Input name="displayOrder" type="number" defaultValue={item?.displayOrder??0}/></Field>{kind==='payment-terms'?<><Field label="Vade Günü"><Input name="dueDays" type="number" min="0" defaultValue={item?.dueDays??0}/></Field><Field label="İskonto Günü"><Input name="discountDays" type="number" min="0" defaultValue={item?.discountDays??''}/></Field><Field label="İskonto Oranı"><Input name="discountRate" type="number" min="0" step="0.01" defaultValue={item?.discountRate??''}/></Field></>:null}{kind==='currencies'?<><Field label="ISO Kodu"><Input name="isoCode" maxLength={3} defaultValue={item?.isoCode??''}/></Field><Field label="Sembol"><Input name="symbol" defaultValue={item?.symbol??''}/></Field><Field label="Ondalık Basamak"><Input name="decimalPlaces" type="number" min="0" max="6" defaultValue={item?.decimalPlaces??2}/></Field></>:null}<div className="sm:col-span-2"><Field label="Açıklama"><Textarea name="description" defaultValue={item?.description??''}/></Field></div></div><div className="flex flex-wrap gap-5"><Check name="isActive" label="Aktif" defaultChecked={item?.isActive??true}/><Check name="isDefault" label="Varsayılan" defaultChecked={item?.isDefault??false}/>{kind==='tax-groups'?<Check name="isTaxExempt" label="Vergiden Muaf" defaultChecked={item?.isTaxExempt??false}/>:null}</div><DialogFooter><Button type="button" variant="outline" onClick={()=>onOpenChange(false)}>Vazgeç</Button><Button type="submit" disabled={saving}>{saving?'Kaydediliyor...':'Kaydet'}</Button></DialogFooter></form></DialogContent></Dialog>}
function Field({label,children}:{label:string;children:ReactElement}):ReactElement{return <div className="space-y-2"><Label>{label}</Label>{children}</div>}
function Check({name,label,defaultChecked}:{name:string;label:string;defaultChecked:boolean}):ReactElement{return <label className="flex items-center gap-2 text-sm font-medium"><input type="checkbox" name={name} defaultChecked={defaultChecked} className="h-4 w-4"/>{label}</label>}
