import { useEffect, useState, type FormEvent, type ReactElement } from "react";
import { useQuery } from "@tanstack/react-query";
import { ArrowLeft, Save } from "lucide-react";
import { useNavigate, useParams } from "react-router-dom";
import { useTranslation } from "react-i18next";
import type { TFunction } from "i18next";
import { toast } from "sonner";
import { api } from "@/lib/axios";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { VoiceSearchCombobox } from "@/components/shared/VoiceSearchCombobox";
import { ErpLookupCombobox } from "@/features/erp-form-management/ErpLookupCombobox";
import { ErpPagedManagementPage, type ErpPageConfig } from "@/features/erp-operation-management";

type Envelope<T> = { data: T };
type FiscalPeriod = { id?: number; code: string; name: string; startDate: string; endDate: string; isOpen: boolean; isInventoryClosed: boolean; isGeneralLedgerClosed: boolean };
type PostingProfile = { id?: number; code: string; name: string; movementType: number | string; debitAccountId: number | ""; creditAccountId: number | ""; productGroupId: number | ""; warehouseId: number | ""; priority: number; isActive: boolean };
const movementTypes = ["Opening","PurchaseReceipt","PurchaseReturn","SalesShipment","SalesReturn","TransferIssue","TransferReceipt","CountGain","CountLoss","AdjustmentIn","AdjustmentOut"];
const movementValues: Record<string, number> = { Opening:10, PurchaseReceipt:20, PurchaseReturn:21, SalesShipment:30, SalesReturn:31, TransferIssue:40, TransferReceipt:41, CountGain:50, CountLoss:51, AdjustmentIn:60, AdjustmentOut:61 };

const fiscalConfig = (t:TFunction): ErpPageConfig => ({
  pageKey:"fiscal-periods", title:t("accountingDefinitions.fiscal.listTitle"), eyebrow:t("accountingDefinitions.eyebrow"), description:t("accountingDefinitions.fiscal.listDescription"),
  endpoint:"/api/accounting/definitions/fiscal-periods", accent:"violet", createLabel:t("accountingDefinitions.fiscal.createLabel"), createPath:"/accounting/definitions/fiscal-periods/new",
  columns:[{key:"id",label:t("fields.id"),format:"id",sortable:true,width:100},{key:"code",label:t("accountingDefinitions.code")},{key:"name",label:t("accountingDefinitions.name")},{key:"startDate",label:t("accountingDefinitions.startDate"),format:"date"},{key:"endDate",label:t("accountingDefinitions.endDate"),format:"date"},{key:"isOpen",label:t("accountingDefinitions.isOpen"),format:"boolean"},{key:"isInventoryClosed",label:t("accountingDefinitions.isInventoryClosed"),format:"boolean"},{key:"isGeneralLedgerClosed",label:t("accountingDefinitions.isGeneralLedgerClosed"),format:"boolean"}],
  actions:[{label:t("common.edit",{defaultValue:"Düzenle"}),kind:"update",navigateTo:r=>`/accounting/definitions/fiscal-periods/${r.id}/edit`},{label:t("common.delete.action",{defaultValue:"Sil"}),kind:"delete",method:"delete",endpoint:r=>`/api/accounting/definitions/fiscal-periods/${r.id}`,confirm:t("accountingDefinitions.fiscal.deleteConfirm"),variant:"destructive"}]
});
const profileConfig = (t:TFunction): ErpPageConfig => ({
  pageKey:"inventory-posting-profiles", title:t("accountingDefinitions.profile.listTitle"), eyebrow:t("accountingDefinitions.eyebrow"), description:t("accountingDefinitions.profile.listDescription"),
  endpoint:"/api/accounting/definitions/inventory-posting-profiles", accent:"violet", createLabel:t("accountingDefinitions.profile.createLabel"), createPath:"/accounting/definitions/inventory-posting-profiles/new",
  columns:[{key:"id",label:t("fields.id"),format:"id",sortable:true,width:100},{key:"code",label:t("accountingDefinitions.code")},{key:"name",label:t("accountingDefinitions.name")},{key:"movementType",label:t("accountingDefinitions.movementType"),format:"status"},{key:"debitAccount",label:t("accountingDefinitions.debitAccount"),sortable:false},{key:"creditAccount",label:t("accountingDefinitions.creditAccount"),sortable:false},{key:"productGroup",label:t("accountingDefinitions.productGroup"),sortable:false},{key:"warehouse",label:t("accountingDefinitions.warehouse"),sortable:false},{key:"priority",label:t("accountingDefinitions.priority")},{key:"isActive",label:t("accountingDefinitions.isActive"),format:"boolean"}],
  actions:[{label:t("common.edit",{defaultValue:"Düzenle"}),kind:"update",navigateTo:r=>`/accounting/definitions/inventory-posting-profiles/${r.id}/edit`},{label:t("common.delete.action",{defaultValue:"Sil"}),kind:"delete",method:"delete",endpoint:r=>`/api/accounting/definitions/inventory-posting-profiles/${r.id}`,confirm:t("accountingDefinitions.profile.deleteConfirm"),variant:"destructive"}]
});
export function FiscalPeriodManagementPage(){const{t}=useTranslation("erp");return <ErpPagedManagementPage config={fiscalConfig(t)}/>}
export function InventoryPostingProfileManagementPage(){const{t}=useTranslation("erp");return <ErpPagedManagementPage config={profileConfig(t)}/>}
export function FiscalPeriodFormPage(){return <DefinitionForm kind="fiscal"/>}
export function InventoryPostingProfileFormPage(){return <DefinitionForm kind="profile"/>}

function DefinitionForm({kind}:{kind:"fiscal"|"profile"}):ReactElement{
  const {id}=useParams(); const editing=Boolean(id); const navigate=useNavigate(); const {t}=useTranslation("erp");
  const endpoint=kind==="fiscal"?"/api/accounting/definitions/fiscal-periods":"/api/accounting/definitions/inventory-posting-profiles";
  const returnPath=kind==="fiscal"?"/accounting/definitions/fiscal-periods":"/accounting/definitions/inventory-posting-profiles";
  const emptyFiscal:FiscalPeriod={code:"",name:"",startDate:new Date().getFullYear()+"-01-01",endDate:new Date().getFullYear()+"-12-31",isOpen:true,isInventoryClosed:false,isGeneralLedgerClosed:false};
  const emptyProfile:PostingProfile={code:"",name:"",movementType:20,debitAccountId:"",creditAccountId:"",productGroupId:"",warehouseId:"",priority:100,isActive:true};
  const [form,setForm]=useState<FiscalPeriod|PostingProfile>(kind==="fiscal"?emptyFiscal:emptyProfile); const [saving,setSaving]=useState(false);
  const query=useQuery({queryKey:["accounting-definition",kind,id],enabled:editing,queryFn:async()=>{const response=await api.get<Envelope<FiscalPeriod|PostingProfile>>(`${endpoint}/${id}`);return response.data}});
  useEffect(()=>{if(query.data)setForm(kind==="profile"?{...query.data,movementType:movementValues[String((query.data as PostingProfile).movementType)]??(query.data as PostingProfile).movementType}:query.data)},[query.data,kind]);
  const set=(key:string,value:unknown)=>setForm(current=>({...current,[key]:value}));
  const submit=async(event:FormEvent)=>{event.preventDefault();try{setSaving(true);const profile=form as PostingProfile;const body=kind==="profile"?{...profile,movementType:Number(profile.movementType),debitAccountId:Number(profile.debitAccountId),creditAccountId:Number(profile.creditAccountId),productGroupId:Number(profile.productGroupId)>0?Number(profile.productGroupId):null,warehouseId:Number(profile.warehouseId)>0?Number(profile.warehouseId):null}:form;if(editing)await api.put(`${endpoint}/${id}`,body);else await api.post(endpoint,body);toast.success(t("accountingDefinitions.saved"));navigate(returnPath)}catch(error){toast.error(error instanceof Error?error.message:t("common.createError"))}finally{setSaving(false)}};
  if(editing&&query.isLoading)return <div className="metivon-panel rounded-3xl p-8">{t("common.loading")}</div>;
  return <div className="mx-auto max-w-5xl space-y-5"><section className="metivon-hero rounded-3xl p-6 md:p-8"><button type="button" onClick={()=>navigate(returnPath)} className="mb-4 inline-flex items-center gap-2 text-sm text-white/80"><ArrowLeft className="h-4 w-4"/>{t("common.backToList")}</button><h1 className="text-3xl font-semibold">{t(`accountingDefinitions.${kind}.${editing?"edit":"create"}`)}</h1><p className="mt-2 text-white/75">{t(`accountingDefinitions.${kind}.formDescription`)}</p></section><form onSubmit={submit} className="metivon-panel space-y-5 rounded-2xl border p-5"><div className="grid gap-4 md:grid-cols-2"><TextField label={t("accountingDefinitions.code")} value={String(form.code)} required onChange={v=>set("code",v)}/><TextField label={t("accountingDefinitions.name")} value={String(form.name)} required onChange={v=>set("name",v)}/>{kind==="fiscal"?<FiscalFields form={form as FiscalPeriod} set={set} t={t}/>:<ProfileFields form={form as PostingProfile} set={set} t={t}/>}</div><div className="flex flex-col-reverse gap-3 sm:flex-row sm:justify-end"><Button type="button" variant="outline" onClick={()=>navigate(returnPath)}>{t("common.cancel")}</Button><Button type="submit" disabled={saving}><Save/>{saving?t("common.saving"):t("accountingDefinitions.save")}</Button></div></form></div>
}
function FiscalFields({form,set,t}:{form:FiscalPeriod;set:(k:string,v:unknown)=>void;t:(key:string,options?:Record<string,unknown>)=>string}){return <><TextField label={t("accountingDefinitions.startDate")} type="date" value={form.startDate} required onChange={v=>set("startDate",v)}/><TextField label={t("accountingDefinitions.endDate")} type="date" value={form.endDate} required onChange={v=>set("endDate",v)}/><Toggle label={t("accountingDefinitions.isOpen")} checked={form.isOpen} onChange={v=>set("isOpen",v)}/><Toggle label={t("accountingDefinitions.isInventoryClosed")} checked={form.isInventoryClosed} onChange={v=>set("isInventoryClosed",v)}/><Toggle label={t("accountingDefinitions.isGeneralLedgerClosed")} checked={form.isGeneralLedgerClosed} onChange={v=>set("isGeneralLedgerClosed",v)}/></>}
function ProfileFields({form,set,t}:{form:PostingProfile;set:(k:string,v:unknown)=>void;t:(key:string,options?:Record<string,unknown>)=>string}){const options=movementTypes.map(x=>({value:String(movementValues[x]),label:t(`statuses.${x}`,{defaultValue:x})}));return <><div className="space-y-2"><Label>{t("accountingDefinitions.movementType")} *</Label><VoiceSearchCombobox options={options} value={String(form.movementType)} onSelect={v=>set("movementType",Number(v))} placeholder={t("common.select")} searchPlaceholder={t("common.searchPlaceholder")} disableToggleOff modal/></div><Lookup label={t("accountingDefinitions.debitAccount")} lookup="ledgeraccounts" value={form.debitAccountId} required set={v=>set("debitAccountId",v)} t={t}/><Lookup label={t("accountingDefinitions.creditAccount")} lookup="ledgeraccounts" value={form.creditAccountId} required set={v=>set("creditAccountId",v)} t={t}/><Lookup label={t("accountingDefinitions.productGroup")} lookup="productgroups" value={form.productGroupId} set={v=>set("productGroupId",v)} t={t}/><Lookup label={t("accountingDefinitions.warehouse")} lookup="warehouses" value={form.warehouseId} set={v=>set("warehouseId",v)} t={t}/><TextField label={t("accountingDefinitions.priority")} type="number" value={String(form.priority)} required onChange={v=>set("priority",Number(v))}/><Toggle label={t("accountingDefinitions.isActive")} checked={form.isActive} onChange={v=>set("isActive",v)}/></>}
function TextField({label,value,onChange,type="text",required=false}:{label:string;value:string;onChange:(v:string)=>void;type?:string;required?:boolean}){return <div className="space-y-2"><Label>{label}{required?" *":""}</Label><Input type={type} value={value} required={required} onChange={e=>onChange(e.target.value)}/></div>}
function Toggle({label,checked,onChange}:{label:string;checked:boolean;onChange:(v:boolean)=>void}){return <label className="flex min-h-11 items-center gap-3 rounded-xl border bg-muted/20 px-4 py-3"><input type="checkbox" checked={checked} onChange={e=>onChange(e.target.checked)}/><span className="text-sm font-medium">{label}</span></label>}
function Lookup({label,lookup,value,set,required=false,t}:{label:string;lookup:string;value:number|"";set:(v:number|"")=>void;required?:boolean;t:(key:string)=>string}){return <div className="space-y-2"><Label>{label}{required?" *":""}</Label><ErpLookupCombobox lookupKey={lookup} value={String(value)} fallbackOptions={[]} placeholder={t("common.select")} searchPlaceholder={t("common.searchPlaceholder")} required={required} onChange={set}/></div>}
