import { useEffect, useState, type FormEvent, type ReactElement } from 'react';
import { Link, useParams } from 'react-router-dom';
import { useTranslation } from 'react-i18next';
import { api } from '@/lib/axios';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { formatSystemCurrency, parseSystemNumber } from '@/lib/system-settings';

type Detail={dossier:{id:number;dossierNumber:string;status:string;supplier:string;currencyCode:string;incotermCode:string;customsDeclarationNumber?:string;customsDeclarationDate?:string;customsExchangeRate:number;openDate:string;notes?:string};lines:Array<Record<string,unknown>>;costs:Array<{id:number;costType:string;sourceType:string;invoiceNumber?:string;paymentReference?:string;localAmount:number;currencyCode:string}>;documents:Array<{id:number;documentType:string;documentNumber?:string;originalFileName:string;downloadUrl:string;createdAt:string}>;timeline:Array<{at:string;kind:string;title:string;detail:string}>;totals:{goods:number;costs:number;final:number}};
type Envelope<T>={data:T};
const documentTypes=['CustomsDeclaration','CommercialInvoice','FreightDocument','InsurancePolicy','CertificateOfOrigin','PaymentReceipt','BankReceipt','PurchaseInvoice','InspectionCertificate','Other'];

export function ImportDossierDetailPage():ReactElement{
 const{id}=useParams();const{t}=useTranslation('erp');const[data,setData]=useState<Detail|null>(null);const[busy,setBusy]=useState(false);const[file,setFile]=useState<File|null>(null);const[documentType,setDocumentType]=useState('CustomsDeclaration');const[documentNumber,setDocumentNumber]=useState('');const[customs,setCustoms]=useState({number:'',date:'',exchangeRate:'1',actualArrivalDate:''});
 const load=async()=>{const response=await api.get<Envelope<Detail>>(`/api/import-dossiers/${id}`);setData(response.data);};useEffect(()=>{void load();},[id]);
 const upload=async(e:FormEvent)=>{e.preventDefault();if(!file)return;setBusy(true);try{const form=new FormData();form.append('documentType',String(documentTypes.indexOf(documentType)+1));form.append('documentNumber',documentNumber);form.append('file',file);await api.post(`/api/import-dossiers/${id}/documents`,form);setFile(null);setDocumentNumber('');await load();}finally{setBusy(false);}};
 const saveCustoms=async(e:FormEvent)=>{e.preventDefault();setBusy(true);try{await api.put(`/api/import-dossiers/${id}/customs-declaration`,{number:customs.number,date:customs.date,exchangeRate:parseSystemNumber(customs.exchangeRate),actualArrivalDate:customs.actualArrivalDate||null});await load();}finally{setBusy(false);}};
 if(!data)return <div className="p-8">{t('common.loading')}</div>;
 const money=(value:number)=>formatSystemCurrency(value,data.dossier.currencyCode);
 return <div className="space-y-6">
  <section className="rounded-3xl bg-gradient-to-br from-cyan-950 via-slate-950 to-blue-950 p-7 text-white"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[.24em] text-cyan-200">{t('pages.import-dossiers.eyebrow')}</p><h1 className="mt-2 text-3xl font-semibold">{data.dossier.dossierNumber}</h1><p className="mt-2 text-slate-300">{data.dossier.supplier} · {data.dossier.incotermCode} · {data.dossier.currencyCode} · {t(`statuses.${data.dossier.status}`)}</p></div><div className="flex gap-2"><Button asChild variant="secondary"><Link to={`/import-dossiers/${id}/costs/new`}>{t('pages.import-dossiers.actions.1.label')}</Link></Button><Button asChild variant="outline"><Link to="/import-dossiers">{t('common.backToList')}</Link></Button></div></div></section>
  <section className="grid gap-4 md:grid-cols-3">{[['goodsAmount',data.totals.goods],['landedCostAmount',data.totals.costs],['finalAmount',data.totals.final]].map(([key,value])=><div className="rounded-2xl border bg-card p-5" key={String(key)}><p className="text-sm text-muted-foreground">{t(`fields.${key}`)}</p><p className="mt-2 text-2xl font-semibold">{money(Number(value))}</p></div>)}</section>
  <section className="grid gap-6 xl:grid-cols-2"><form onSubmit={saveCustoms} className="space-y-4 rounded-2xl border bg-card p-6"><h2 className="text-lg font-semibold">{t('fields.customsDeclarationNumber')}</h2><div className="grid gap-4 sm:grid-cols-2"><div><Label>{t('fields.customsDeclarationNumber')}</Label><Input required value={customs.number} onChange={e=>setCustoms(v=>({...v,number:e.target.value}))}/></div><div><Label>{t('fields.customsDeclarationDate')}</Label><Input required type="date" value={customs.date} onChange={e=>setCustoms(v=>({...v,date:e.target.value}))}/></div><div><Label>{t('fields.customsExchangeRate')}</Label><Input required type="number" step="0.000001" value={customs.exchangeRate} onChange={e=>setCustoms(v=>({...v,exchangeRate:e.target.value}))}/></div><div><Label>{t('fields.actualArrivalDate')}</Label><Input type="date" value={customs.actualArrivalDate} onChange={e=>setCustoms(v=>({...v,actualArrivalDate:e.target.value}))}/></div></div><Button disabled={busy}>{t('common.saving')}</Button></form>
  <form onSubmit={upload} className="space-y-4 rounded-2xl border bg-card p-6"><h2 className="text-lg font-semibold">{t('fields.documents')}</h2><div><Label>{t('fields.documentType')}</Label><select className="mt-2 h-10 w-full rounded-md border bg-background px-3" value={documentType} onChange={e=>setDocumentType(e.target.value)}>{documentTypes.map(x=><option key={x} value={x}>{t(`documentTypes.${x}`)}</option>)}</select></div><div><Label>{t('fields.documentNumber')}</Label><Input value={documentNumber} onChange={e=>setDocumentNumber(e.target.value)}/></div><div><Label>{t('fields.file')}</Label><Input required accept=".pdf,.jpg,.jpeg,.png" type="file" onChange={e=>setFile(e.target.files?.[0]??null)}/></div><Button disabled={busy||!file}>{t('fields.uploadDocument')}</Button></form></section>
  <section className="grid gap-6 xl:grid-cols-2"><div className="rounded-2xl border bg-card p-6"><h2 className="mb-4 text-lg font-semibold">{t('fields.costHistory')}</h2><div className="space-y-3">{data.costs.map(x=><div key={x.id} className="flex justify-between rounded-xl bg-muted/50 p-4"><div><p className="font-medium">{x.costType}</p><p className="text-sm text-muted-foreground">{t(`sourceTypes.${x.sourceType}`)} · {x.invoiceNumber||x.paymentReference}</p></div><strong>{money(x.localAmount)}</strong></div>)}</div></div><div className="rounded-2xl border bg-card p-6"><h2 className="mb-4 text-lg font-semibold">{t('fields.documents')}</h2><div className="space-y-3">{data.documents.map(x=><a className="block rounded-xl bg-muted/50 p-4 hover:bg-muted" href={x.downloadUrl} key={x.id}><p className="font-medium">{t(`documentTypes.${x.documentType}`)}</p><p className="text-sm text-muted-foreground">{x.originalFileName} · {x.documentNumber}</p></a>)}</div></div></section>
  <section className="rounded-2xl border bg-card p-6"><h2 className="mb-4 text-lg font-semibold">{t('fields.dossierStory')}</h2><div className="border-s ps-5">{data.timeline.map((x,i)=><div className="relative mb-5" key={`${x.kind}-${i}`}><span className="absolute -start-[25px] top-1 h-3 w-3 rounded-full bg-cyan-500"/><p className="font-medium">{x.title}</p><p className="text-sm text-muted-foreground">{x.detail}</p></div>)}</div></section>
 </div>;
}
