import { useCallback, useEffect, useState, type FormEvent } from "react";
import { Link, useParams } from "react-router-dom";
import { FileText, Landmark, Link2, Plus, Timer, Trash2, Upload } from "lucide-react";
import { useTranslation } from "react-i18next";
import { api } from "@/lib/axios";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { ErpLookupCombobox } from "@/features/erp-form-management/ErpLookupCombobox";
import { toast } from "sonner";

type Envelope<T> = { data: T };
type Declaration = { id: number; declarationNumber: string; declarationType: string; status: string; regimeCode: string; customsOfficeCode: string; declarationDate: string; quantity: number; releasedQuantity: number };
type Detail = {
  dossier: { id: number; dossierNumber: string; direction: string; operationType: string; status: string; businessPartner: string; currencyCode: string; incotermCode: string };
  declarations: Declaration[];
  history: Array<{ id: number; fromStatus: string; toStatus: string; occurredAt: string; reasonCode?: string }>;
  links: Array<{ id: number; linkType: string; referenceNumber?: string; linkedQuantity?: number }>;
  attachments: Array<{ id: number; attachmentType: string; originalFileName: string; fileSize: number; downloadUrl: string }>;
  customsWaitingHours?: number;
};
type DeclarationLine = { productId: number | null; unitId: number | null; gtipCode: string; countryOfOriginCode: string; quantity: string; netWeight: string; grossWeight: string; packageCount: string; customsValue: string; customsDuty: string; vatAmount: string };

const emptyLine = (): DeclarationLine => ({ productId: null, unitId: null, gtipCode: "", countryOfOriginCode: "", quantity: "1", netWeight: "0", grossWeight: "0", packageCount: "0", customsValue: "0", customsDuty: "0", vatAmount: "0" });
const dossierTransitions: Record<string, Array<{ value: number; status: string }>> = {
  Draft: [{ value: 10, status: "Booked" }], Booked: [{ value: 20, status: "InTransit" }, { value: 30, status: "Arrived" }], InTransit: [{ value: 30, status: "Arrived" }],
  Arrived: [{ value: 40, status: "TemporaryStorage" }, { value: 50, status: "CustomsWaiting" }], TemporaryStorage: [{ value: 50, status: "CustomsWaiting" }, { value: 60, status: "Inspection" }],
  CustomsWaiting: [{ value: 60, status: "Inspection" }, { value: 70, status: "TaxWaiting" }, { value: 80, status: "ReleaseWaiting" }], Inspection: [{ value: 70, status: "TaxWaiting" }, { value: 80, status: "ReleaseWaiting" }],
  TaxWaiting: [{ value: 80, status: "ReleaseWaiting" }], ReleaseWaiting: [{ value: 90, status: "Released" }, { value: 100, status: "ExitAuthorized" }], Released: [{ value: 110, status: "Completed" }], ExitAuthorized: [{ value: 110, status: "Completed" }], Completed: [{ value: 120, status: "Closed" }],
};
const declarationTransitions: Record<string, Array<{ value: number; status: string }>> = {
  Registered: [{ value: 20, status: "Inspection" }, { value: 30, status: "TaxCalculated" }], Inspection: [{ value: 30, status: "TaxCalculated" }], TaxCalculated: [{ value: 40, status: "TaxPaid" }], TaxPaid: [{ value: 50, status: "ReleaseWaiting" }], ReleaseWaiting: [{ value: 60, status: "Released" }], Released: [{ value: 70, status: "Closed" }],
};

export function TradeDossierDetailPage() {
  const { id } = useParams(); const { t } = useTranslation("erp");
  const [data, setData] = useState<Detail>(); const [busy, setBusy] = useState(false); const [showDeclaration, setShowDeclaration] = useState(false);
  const [file, setFile] = useState<File>(); const [documentNumber, setDocumentNumber] = useState("");
  const [declaration, setDeclaration] = useState({ declarationType: "1", declarationNumber: "", declarationDate: new Date().toISOString().slice(0, 10), regimeCode: "", customsOfficeCode: "", customsExchangeRate: "1", guaranteeReference: "", registrationNumber: "", inspectionChannel: "0", totalTaxes: "0", notes: "" });
  const [lines, setLines] = useState<DeclarationLine[]>([emptyLine()]);
  const load = useCallback(async () => { const response = await api.get<Envelope<Detail>>(`/api/trade-dossiers/${id}`); setData(response.data); }, [id]);
  useEffect(() => { void load(); }, [load]);
  const changeDossierStatus = async (value: number) => { setBusy(true); try { await api.post(`/api/trade-dossiers/${id}/status`, { status: value, occurredAt: new Date().toISOString(), reasonCode: null, plannedAt: null, responsiblePartnerId: null, notes: null }); await load(); toast.success(t("common.createSuccess")); } finally { setBusy(false); } };
  const changeDeclarationStatus = async (declarationId: number, value: number) => { setBusy(true); try { await api.post(`/api/trade-dossiers/${id}/declarations/${declarationId}/status`, { status: value, occurredAt: new Date().toISOString(), notes: null }); await load(); toast.success(t("common.createSuccess")); } finally { setBusy(false); } };
  const submitDeclaration = async (event: FormEvent) => { event.preventDefault(); if (lines.some(x => !x.productId || !x.unitId || !x.gtipCode || Number(x.quantity) <= 0)) { toast.error(t("common.createError")); return; } setBusy(true); try { await api.post(`/api/trade-dossiers/${id}/declarations`, { ...declaration, declarationType: Number(declaration.declarationType), customsExchangeRate: Number(declaration.customsExchangeRate), inspectionChannel: Number(declaration.inspectionChannel), totalTaxes: Number(declaration.totalTaxes), bondedWarehouseId: null, lines: lines.map(x => ({ ...x, productId: x.productId, unitId: x.unitId, quantity: Number(x.quantity), netWeight: Number(x.netWeight), grossWeight: Number(x.grossWeight), packageCount: Number(x.packageCount), customsValue: Number(x.customsValue), customsDuty: Number(x.customsDuty), vatAmount: Number(x.vatAmount) })) }); setShowDeclaration(false); setLines([emptyLine()]); await load(); toast.success(t("common.createSuccess")); } finally { setBusy(false); } };
  const upload = async (event: FormEvent) => { event.preventDefault(); if (!file) return; setBusy(true); try { const form = new FormData(); form.append("attachmentType", "99"); form.append("documentNumber", documentNumber); form.append("file", file); await api.post(`/api/trade-dossiers/${id}/attachments`, form); setFile(undefined); setDocumentNumber(""); await load(); toast.success(t("common.createSuccess")); } finally { setBusy(false); } };
  if (!data) return <div className="metivon-panel rounded-2xl border p-8">{t("common.loading")}</div>;
  const dossier = data.dossier;
  return <div className="space-y-5">
    <section className="metivon-hero rounded-3xl p-6 text-white"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[.2em] text-white/70">{t("pages.trade-dossiers.eyebrow")}</p><h1 className="mt-2 text-3xl font-semibold">{dossier.dossierNumber}</h1><p className="mt-2 text-white/75">{t(`statuses.${dossier.direction}`)} · {t(`statuses.${dossier.operationType}`)} · {dossier.businessPartner} · {dossier.incotermCode}</p></div><div className="flex flex-wrap gap-2">{(dossierTransitions[dossier.status] ?? []).map(x => <Button key={x.value} disabled={busy} variant="secondary" onClick={() => void changeDossierStatus(x.value)}>{t(`statuses.${x.status}`)}</Button>)}<Button asChild variant="outline"><Link to="/trade-dossiers">{t("common.backToList")}</Link></Button></div></div></section>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Card icon={<Landmark />} label={t("fields.status")} value={t(`statuses.${dossier.status}`)} /><Card icon={<Timer />} label={t("fields.customsWaitingHours")} value={data.customsWaitingHours == null ? "—" : `${data.customsWaitingHours.toFixed(1)} h`} /><Card icon={<FileText />} label={t("fields.declarationCount")} value={String(data.declarations.length)} /><Card icon={<Link2 />} label={t("fields.linkedDocumentCount")} value={String(data.links.length)} /></div>
    <section className="metivon-panel rounded-2xl border p-5"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="text-lg font-semibold">{t("documentTypes.CustomsDeclaration")}</h2><Button onClick={() => setShowDeclaration(value => !value)}><Plus />{t("common.addLine")}</Button></div>
      {showDeclaration && <DeclarationForm value={declaration} setValue={setDeclaration} lines={lines} setLines={setLines} busy={busy} onSubmit={submitDeclaration} t={t} />}
      <div className="mt-4 space-y-3">{data.declarations.length ? data.declarations.map(item => <div key={item.id} className="rounded-xl border p-4"><div className="flex flex-wrap justify-between gap-3"><div><b>{item.declarationNumber}</b><p className="mt-1 text-sm text-muted-foreground">{t(`statuses.${item.declarationType}`)} · {item.regimeCode} · {item.customsOfficeCode} · {item.declarationDate}</p></div><span className="h-fit rounded-full bg-muted px-3 py-1 text-xs">{t(`statuses.${item.status}`)}</span></div><p className="mt-2 text-sm">{t("fields.quantity")}: {item.quantity} / {t("statuses.Released")}: {item.releasedQuantity}</p><div className="mt-3 flex flex-wrap gap-2">{(declarationTransitions[item.status] ?? []).map(x => <Button key={x.value} size="sm" variant="outline" disabled={busy} onClick={() => void changeDeclarationStatus(item.id, x.value)}>{t(`statuses.${x.status}`)}</Button>)}</div></div>) : <p className="mt-4 text-sm text-muted-foreground">{t("common.empty")}</p>}</div>
    </section>
    <div className="grid gap-5 lg:grid-cols-2"><section className="metivon-panel rounded-2xl border p-5"><h2 className="text-lg font-semibold">{t("fields.uploadDocument")}</h2><form onSubmit={upload} className="mt-4 space-y-3"><Input value={documentNumber} onChange={event => setDocumentNumber(event.target.value)} placeholder={t("fields.documentNumber")} /><Input type="file" accept=".pdf,.jpg,.jpeg,.png,.xlsx,.xml" onChange={event => setFile(event.target.files?.[0])} /><Button className="w-full" disabled={busy || !file}><Upload />{t("fields.uploadDocument")}</Button></form></section><section className="metivon-panel rounded-2xl border p-5"><h2 className="text-lg font-semibold">{t("fields.documents")}</h2><div className="mt-4 space-y-2">{data.attachments.map(item => <a key={item.id} className="flex justify-between rounded-xl border p-3 hover:bg-muted" href={item.downloadUrl}><span>{item.originalFileName}</span><span className="text-xs text-muted-foreground">{Math.ceil(item.fileSize / 1024)} KB</span></a>)}</div></section></div>
    <section className="metivon-panel rounded-2xl border p-5"><h2 className="text-lg font-semibold">{t("fields.dossierStory")}</h2><div className="mt-4 space-y-3">{data.history.map(item => <div key={item.id} className="border-s-2 ps-4"><b>{t(`statuses.${item.fromStatus}`)} → {t(`statuses.${item.toStatus}`)}</b><p className="text-xs text-muted-foreground">{new Date(item.occurredAt).toLocaleString()} {item.reasonCode ? `· ${item.reasonCode}` : ""}</p></div>)}</div></section>
  </div>;
}

function DeclarationForm({ value, setValue, lines, setLines, busy, onSubmit, t }: { value: Record<string, string>; setValue: React.Dispatch<React.SetStateAction<any>>; lines: DeclarationLine[]; setLines: React.Dispatch<React.SetStateAction<DeclarationLine[]>>; busy: boolean; onSubmit: (event: FormEvent) => void; t: (key: string) => string }) {
  const updateLine = (index: number, patch: Partial<DeclarationLine>) => setLines(current => current.map((line, lineIndex) => lineIndex === index ? { ...line, ...patch } : line));
  return <form onSubmit={onSubmit} className="mt-5 space-y-4 rounded-2xl border bg-muted/20 p-4"><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-4"><select className="h-10 rounded-md border bg-background px-3" value={value.declarationType} onChange={event => setValue((current: any) => ({ ...current, declarationType: event.target.value }))}><option value="1">{t("statuses.Import")}</option><option value="2">{t("statuses.Export")}</option><option value="3">{t("statuses.TemporaryStorage")}</option><option value="4">Transit</option><option value="5">{t("statuses.ReExport")}</option></select><select className="h-10 rounded-md border bg-background px-3" value={value.inspectionChannel} onChange={event => setValue((current: any) => ({ ...current, inspectionChannel: event.target.value }))}><option value="0">—</option><option value="1">Blue</option><option value="2">Green</option><option value="3">Yellow</option><option value="4">Red</option></select>{["declarationNumber", "registrationNumber", "declarationDate", "regimeCode", "customsOfficeCode", "customsExchangeRate", "totalTaxes", "guaranteeReference"].map(key => <Input key={key} required={!["guaranteeReference", "registrationNumber"].includes(key)} type={key === "declarationDate" ? "date" : ["customsExchangeRate", "totalTaxes"].includes(key) ? "number" : "text"} step={["customsExchangeRate", "totalTaxes"].includes(key) ? "0.000001" : undefined} value={value[key]} onChange={event => setValue((current: any) => ({ ...current, [key]: event.target.value }))} placeholder={t(`fields.${key}`)} />)}</div>
    {lines.map((line, index) => <div key={index} className="grid gap-3 rounded-xl border bg-background p-3 md:grid-cols-2 xl:grid-cols-6"><ErpLookupCombobox lookupKey="products" value={line.productId ? String(line.productId) : ""} fallbackOptions={[]} searchPlaceholder={t("common.searchPlaceholder")} required invalid={!line.productId} placeholder={t("fields.productId")} onChange={selected => updateLine(index, { productId: selected === "" ? null : selected })} /><ErpLookupCombobox lookupKey="units" value={line.unitId ? String(line.unitId) : ""} fallbackOptions={[]} searchPlaceholder={t("common.searchPlaceholder")} required invalid={!line.unitId} placeholder={t("fields.unitId")} onChange={selected => updateLine(index, { unitId: selected === "" ? null : selected })} />{(["gtipCode", "countryOfOriginCode", "quantity", "netWeight", "grossWeight", "packageCount", "customsValue", "customsDuty", "vatAmount"] as const).map(key => <Input key={key} required={["gtipCode", "quantity"].includes(key)} type={["quantity", "netWeight", "grossWeight", "packageCount", "customsValue", "customsDuty", "vatAmount"].includes(key) ? "number" : "text"} min="0" step="0.0001" value={line[key]} onChange={event => updateLine(index, { [key]: event.target.value })} placeholder={t(`fields.${key}`)} />)}<Button type="button" variant="ghost" disabled={lines.length === 1} onClick={() => setLines(current => current.filter((_, lineIndex) => lineIndex !== index))}><Trash2 /></Button></div>)}
    <div className="flex flex-wrap justify-between gap-3"><Button type="button" variant="outline" onClick={() => setLines(current => [...current, emptyLine()])}><Plus />{t("common.addLine")}</Button><Button disabled={busy}>{t("common.saving")}</Button></div></form>;
}

function Card({ icon, label, value }: { icon: React.ReactNode; label: string; value: string }) { return <div className="metivon-panel rounded-2xl border p-4"><div className="flex items-center gap-3 text-muted-foreground">{icon}<span className="text-xs font-semibold uppercase">{label}</span></div><p className="mt-3 text-xl font-semibold">{value}</p></div>; }
