import type { ErpFormConfig, FormValue } from "./types";
const n = (v: FormValue) => Number(v || 0);
const s = (v: FormValue) => (v == null ? "" : String(v));
const b = (v: FormValue) => Boolean(v);
const date = (v: FormValue) => s(v) || null;
export const warehouseForm: ErpFormConfig = {
  title: "Yeni Depo",
  description: "Şubeye bağlı fiziksel veya sanal depo oluşturun.",
  endpoint: "/api/warehouses",
  detailEndpoint: (id) => `/api/warehouses/${id}`,
  updateEndpoint: (id) => `/api/warehouses/${id}/update`,
  returnPath: "/warehouses",
  submitLabel: "Depoyu Oluştur",
  fields: [
    { key: "code", label: "Depo Kodu", type: "text", required: true },
    { key: "name", label: "Depo Adı", type: "text", required: true },
    {
      key: "branchId",
      label: "Şube",
      type: "select",
      lookup: "branches",
      required: true,
    },
    {
      key: "warehouseTypeId",
      label: "Depo Tipi",
      type: "select",
      lookup: "warehouseTypes",
      required: true,
    },
    { key: "city", label: "Şehir", type: "text" },
    {
      key: "countryCode",
      label: "Ülke Kodu",
      type: "text",
      defaultValue: "TR",
    },
    { key: "address", label: "Adres", type: "textarea", span: 2 },
    {
      key: "isWmsEnabled",
      label: "WMS Kullan",
      type: "checkbox",
      defaultValue: true,
    },
    { key: "allowNegativeStock", label: "Negatif Stok", type: "checkbox" },
    { key: "isDefault", label: "Varsayılan Depo", type: "checkbox" },
    { key: "isActive", label: "Aktif", type: "checkbox", defaultValue: true },
  ],
  buildRequest: (h) => ({
    code: s(h.code),
    name: s(h.name),
    branchId: n(h.branchId),
    warehouseTypeId: n(h.warehouseTypeId),
    address: s(h.address) || null,
    city: s(h.city) || null,
    countryCode: s(h.countryCode) || null,
    allowNegativeStock: b(h.allowNegativeStock),
    isWmsEnabled: b(h.isWmsEnabled),
    isDefault: b(h.isDefault),
    isActive: b(h.isActive),
  }),
};
export const locationForm: ErpFormConfig = {
  title: "Yeni Raf / Lokasyon",
  description:
    "Depo içindeki fiziksel adresi ve kapasite sınırlarını tanımlayın.",
  endpoint: "/api/warehouses/locations",
  detailEndpoint: (id) => `/api/warehouses/locations/${id}`,
  updateEndpoint: (id) => `/api/warehouses/locations/${id}/update`,
  returnPath: "/warehouses/locations",
  submitLabel: "Lokasyonu Oluştur",
  fields: [
    {
      key: "warehouseId",
      label: "Depo",
      type: "select",
      lookup: "warehouses",
      required: true,
    },
    {
      key: "warehouseZoneId",
      label: "Depo Bölgesi",
      type: "select",
      lookup: "warehouseZones",
      filterBy: "warehouseId",
      filterItemKey: "warehouseId",
    },
    {
      key: "locationTypeId",
      label: "Lokasyon Tipi",
      type: "select",
      lookup: "locationTypes",
      required: true,
    },
    { key: "code", label: "Lokasyon Kodu", type: "text", required: true },
    { key: "barcode", label: "Barkod", type: "text" },
    { key: "aisle", label: "Koridor", type: "text" },
    { key: "bay", label: "Blok", type: "text" },
    { key: "level", label: "Seviye", type: "text" },
    { key: "position", label: "Pozisyon", type: "text" },
    {
      key: "maximumWeight",
      label: "Maksimum Ağırlık",
      type: "number",
      step: "0.001",
    },
    {
      key: "maximumVolume",
      label: "Maksimum Hacim",
      type: "number",
      step: "0.001",
    },
    {
      key: "maximumQuantity",
      label: "Maksimum Miktar",
      type: "number",
      step: "0.001",
    },
    { key: "isReceiving", label: "Mal Kabul Alanı", type: "checkbox" },
    { key: "isShipping", label: "Sevk Alanı", type: "checkbox" },
    { key: "isQuarantine", label: "Karantina Alanı", type: "checkbox" },
    { key: "isBlocked", label: "Bloke", type: "checkbox" },
    { key: "isActive", label: "Aktif", type: "checkbox", defaultValue: true },
  ],
  buildRequest: (h) => ({
    ...h,
    warehouseId: n(h.warehouseId),
    warehouseZoneId: n(h.warehouseZoneId) || null,
    locationTypeId: n(h.locationTypeId),
    maximumWeight: n(h.maximumWeight) || null,
    maximumVolume: n(h.maximumVolume) || null,
    maximumQuantity: n(h.maximumQuantity) || null,
  }),
};
const purchaseLines = [
  {
    key: "productId",
    label: "Ürün",
    type: "select",
    lookup: "products",
    required: true,
  },
  {
    key: "unitId",
    label: "Birim",
    type: "select",
    lookup: "units",
    required: true,
  },
  {
    key: "storageLocationId",
    label: "Hedef Raf",
    type: "select",
    lookup: "locations",
    filterBy: "warehouseId",
    filterItemKey: "warehouseId",
  },
  {
    key: "quantity",
    label: "Miktar",
    type: "number",
    required: true,
    defaultValue: 1,
    step: "0.001",
  },
  {
    key: "unitPrice",
    label: "Birim Fiyat",
    type: "number",
    required: true,
    defaultValue: 0,
    step: "0.01",
  },
  {
    key: "discountRate",
    label: "İskonto %",
    type: "number",
    defaultValue: 0,
    step: "0.01",
  },
  {
    key: "taxRate",
    label: "KDV %",
    type: "number",
    defaultValue: 20,
    step: "0.01",
  },
  { key: "requestedDeliveryDate", label: "Teslim Tarihi", type: "date" },
  {
    key: "overDeliveryTolerance",
    label: "Fazla Teslim %",
    type: "number",
    defaultValue: 0,
  },
  {
    key: "underDeliveryTolerance",
    label: "Eksik Teslim %",
    type: "number",
    defaultValue: 0,
  },
  { key: "description", label: "Açıklama", type: "text" },
] as const;
export const purchaseForm: ErpFormConfig = {
  title: "Yeni Satın Alma Siparişi",
  description: "Tedarikçi, depo, teslimat ve ürün satırlarını tanımlayın.",
  endpoint: "/api/purchase-orders",
  returnPath: "/purchase-orders",
  submitLabel: "Siparişi Oluştur",
  fields: [
    {
      key: "orderNumber",
      label: "Sipariş No (otomatik olabilir)",
      type: "text",
    },
    {
      key: "branchId",
      label: "Şube",
      type: "select",
      lookup: "branches",
      required: true,
    },
    {
      key: "supplierId",
      label: "Tedarikçi",
      type: "select",
      lookup: "partners",
      required: true,
    },
    { key: "tradeDossierId", label: "Dış Ticaret Dosyası", type: "select", lookup: "tradeDossiers" },
    {
      key: "currencyId",
      label: "Para Birimi",
      type: "select",
      lookup: "currencies",
      required: true,
    },
    {
      key: "paymentTermId",
      label: "Ödeme Koşulu",
      type: "select",
      lookup: "paymentTerms",
      required: true,
    },
    {
      key: "warehouseId",
      label: "Teslim Deposu",
      type: "select",
      lookup: "warehouses",
      required: true,
    },
    { key: "orderDate", label: "Sipariş Tarihi", type: "date", required: true },
    { key: "requestedDeliveryDate", label: "İstenen Teslim", type: "date" },
    { key: "supplierReference", label: "Tedarikçi Referansı", type: "text" },
    { key: "buyerNote", label: "Satın Alma Notu", type: "textarea", span: 2 },
    {
      key: "exchangeRate",
      label: "Kur",
      type: "number",
      defaultValue: 1,
      step: "0.0001",
    },
  ],
  lineFields: [...purchaseLines],
  buildRequest: (h, l) => ({
    orderNumber: s(h.orderNumber) || null,
    orderType: 1,
    branchId: n(h.branchId),
    supplierId: n(h.supplierId),
    tradeDossierId: n(h.tradeDossierId) || null,
    currencyId: n(h.currencyId),
    paymentTermId: n(h.paymentTermId),
    warehouseId: n(h.warehouseId),
    orderDate: s(h.orderDate),
    requestedDeliveryDate: date(h.requestedDeliveryDate),
    supplierReference: s(h.supplierReference) || null,
    buyerNote: s(h.buyerNote) || null,
    exchangeRate: n(h.exchangeRate) || 1,
    lines: l.map((x) => ({
      productId: n(x.productId),
      unitId: n(x.unitId),
      storageLocationId: n(x.storageLocationId) || null,
      description: s(x.description) || null,
      quantity: n(x.quantity),
      unitPrice: n(x.unitPrice),
      discountRate: n(x.discountRate),
      taxRate: n(x.taxRate),
      requestedDeliveryDate: date(x.requestedDeliveryDate),
      overDeliveryTolerance: n(x.overDeliveryTolerance),
      underDeliveryTolerance: n(x.underDeliveryTolerance),
    })),
  }),
};
export const transferForm: ErpFormConfig = {
  title: "Yeni Depo Transferi",
  description:
    "Kaynak ve hedef depo arasında iki aşamalı transfer emri oluşturun.",
  endpoint: "/api/transfer-orders",
  returnPath: "/transfer-orders",
  submitLabel: "Transferi Oluştur",
  fields: [
    {
      key: "transferNumber",
      label: "Transfer No (otomatik olabilir)",
      type: "text",
    },
    { key: "numberSeriesId", label: "Numara Serisi", type: "number-series", numberSeriesModule: "Transfers", numberSeriesReference: "TransferNumber", warehouseField: "fromWarehouseId" },
    {
      key: "fromWarehouseId",
      label: "Kaynak Depo",
      type: "select",
      lookup: "warehouses",
      required: true,
    },
    {
      key: "toWarehouseId",
      label: "Hedef Depo",
      type: "select",
      lookup: "warehouses",
      required: true,
    },
    {
      key: "transferDate",
      label: "Transfer Tarihi",
      type: "date",
      required: true,
    },
    { key: "expectedReceiptDate", label: "Beklenen Teslim", type: "date" },
    { key: "notes", label: "Not", type: "textarea", span: 2 },
  ],
  lineFields: [
    {
      key: "productId",
      label: "Ürün",
      type: "select",
      lookup: "products",
      required: true,
    },
    {
      key: "unitId",
      label: "Birim",
      type: "select",
      lookup: "units",
      required: true,
    },
    {
      key: "fromLocationId",
      label: "Kaynak Raf",
      type: "select",
      lookup: "locations",
      filterBy: "fromWarehouseId",
      filterItemKey: "warehouseId",
      required: true,
    },
    {
      key: "toLocationId",
      label: "Hedef Raf",
      type: "select",
      lookup: "locations",
      filterBy: "toWarehouseId",
      filterItemKey: "warehouseId",
      required: true,
    },
    {
      key: "inventoryStatusId",
      label: "Stok Durumu",
      type: "select",
      lookup: "inventoryStatuses",
      required: true,
    },
    {
      key: "quantity",
      label: "Miktar",
      type: "number",
      required: true,
      defaultValue: 1,
    },
    { key: "inventoryLotId", label: "Lot", type: "select", lookup: "inventoryLots", filterBy: "productId", filterItemKey: "productId" },
    { key: "inventorySerialIds", label: "Stok Serileri", type: "serial-select", lookup: "inventorySerials", quantityField: "quantity", span: 2 },
    { key: "notes", label: "Not", type: "text" },
  ],
  buildRequest: (h, l) => ({
    transferNumber: s(h.transferNumber) || null,
    numberSeriesId: n(h.numberSeriesId) || null,
    fromWarehouseId: n(h.fromWarehouseId),
    toWarehouseId: n(h.toWarehouseId),
    transferDate: s(h.transferDate),
    expectedReceiptDate: date(h.expectedReceiptDate),
    notes: s(h.notes) || null,
    lines: l.map((x) => ({
      productId: n(x.productId),
      unitId: n(x.unitId),
      fromLocationId: n(x.fromLocationId),
      toLocationId: n(x.toLocationId),
      inventoryStatusId: n(x.inventoryStatusId),
      inventoryLotId: n(x.inventoryLotId) || null,
      inventorySerialId: null,
      inventorySerialIds: s(x.inventorySerialIds).split(/[\r\n,;\t]+/).map(Number).filter(Boolean),
      quantity: n(x.quantity),
      notes: s(x.notes) || null,
    })),
  }),
};
export const countForm: ErpFormConfig = {
  title: "Yeni Stok Sayımı",
  description:
    "Depo veya raf bazında sistem miktarlarını dondurarak sayım başlatın.",
  endpoint: "/api/inventory-counts",
  returnPath: "/inventory-counts",
  submitLabel: "Sayımı Başlat",
  fields: [
    { key: "countNumber", label: "Sayım No (otomatik olabilir)", type: "text" },
    {
      key: "warehouseId",
      label: "Depo",
      type: "select",
      lookup: "warehouses",
      required: true,
    },
    {
      key: "storageLocationId",
      label: "Raf (boşsa tüm depo)",
      type: "select",
      lookup: "locations",
      filterBy: "warehouseId",
      filterItemKey: "warehouseId",
    },
    { key: "countDate", label: "Sayım Tarihi", type: "date", required: true },
    {
      key: "isBlindCount",
      label: "Kör Sayım",
      type: "checkbox",
      defaultValue: true,
    },
    { key: "notes", label: "Not", type: "textarea", span: 2 },
  ],
  buildRequest: (h) => ({
    countNumber: s(h.countNumber) || null,
    warehouseId: n(h.warehouseId),
    storageLocationId: n(h.storageLocationId) || null,
    countDate: s(h.countDate),
    isBlindCount: b(h.isBlindCount),
    notes: s(h.notes) || null,
  }),
};
export const priceListForm: ErpFormConfig = {
  title: "Yeni Fiyat Listesi",
  description: "Geçerlilik tarihi, para birimi ve öncelik tanımlayın.",
  endpoint: "/api/pricing/price-lists",
  returnPath: "/pricing/price-lists",
  submitLabel: "Fiyat Listesini Oluştur",
  fields: [
    { key: "code", label: "Liste Kodu", type: "text", required: true },
    { key: "name", label: "Liste Adı", type: "text", required: true },
    { key: "description", label: "Açıklama", type: "textarea", span: 2 },
    {
      key: "currencyId",
      label: "Para Birimi",
      type: "select",
      lookup: "currencies",
      required: true,
    },
    { key: "validFrom", label: "Başlangıç", type: "date", required: true },
    { key: "validTo", label: "Bitiş", type: "date" },
    {
      key: "pricesIncludeTax",
      label: "Fiyatlar Vergi Dahil",
      type: "checkbox",
    },
    { key: "priority", label: "Öncelik", type: "number", defaultValue: 100 },
    { key: "isDefault", label: "Varsayılan", type: "checkbox" },
    { key: "isActive", label: "Aktif", type: "checkbox", defaultValue: true },
  ],
  buildRequest: (h) => ({
    ...h,
    currencyId: n(h.currencyId),
    priority: n(h.priority),
    validTo: date(h.validTo),
  }),
};
export const accountForm: ErpFormConfig = {
  title: "Yeni Muhasebe Hesabı",
  description: "Hesap planına kayıt yapılabilir bir hesap ekleyin.",
  endpoint: "/api/accounting/accounts",
  returnPath: "/accounting/accounts",
  submitLabel: "Hesabı Oluştur",
  fields: [
    { key: "code", label: "Hesap Kodu", type: "text", required: true },
    { key: "name", label: "Hesap Adı", type: "text", required: true },
    {
      key: "accountType",
      label: "Hesap Tipi (1 Varlık, 2 Borç, 3 Özkaynak, 4 Gelir, 5 Gider)",
      type: "number",
      required: true,
      defaultValue: 1,
    },
    {
      key: "parentId",
      label: "Üst Hesap",
      type: "select",
      lookup: "ledgerAccounts",
    },
    {
      key: "allowPosting",
      label: "Kayıt Yapılabilir",
      type: "checkbox",
      defaultValue: true,
    },
    {
      key: "currencyId",
      label: "Para Birimi",
      type: "select",
      lookup: "currencies",
      required: true,
    },
    { key: "isActive", label: "Aktif", type: "checkbox", defaultValue: true },
  ],
  buildRequest: (h) => ({
    ...h,
    accountType: n(h.accountType),
    parentId: n(h.parentId) || null,
    currencyId: n(h.currencyId),
  }),
};
export const receiptForm: ErpFormConfig = {
  title: "Yeni Mal Kabul",
  description: "Satın alma siparişine bağlı veya serbest mal kabul oluşturun.",
  endpoint: "/api/goods-receipts",
  returnPath: "/goods-receipts",
  submitLabel: "Mal Kabulü Oluştur",
  fields: [
    {
      key: "receiptNumber",
      label: "Kabul No (otomatik olabilir)",
      type: "text",
    },
    {
      key: "receiptType",
      label: "Kabul Tipi (1 Sipariş, 2 Serbest)",
      type: "number",
      defaultValue: 1,
      required: true,
    },
    {
      key: "branchId",
      label: "Şube",
      type: "select",
      lookup: "branches",
      required: true,
    },
    {
      key: "supplierId",
      label: "Tedarikçi",
      type: "select",
      lookup: "partners",
    },
    {
      key: "purchaseOrderIds",
      label: "Satın Alma Siparişi",
      type: "multi-select",
      lookup: "purchaseOrders",
    },
    { key: "tradeDossierId", label: "İthalat / Gümrük Dosyası", type: "select", lookup: "tradeDossiers" },
    {
      key: "warehouseId",
      label: "Depo",
      type: "select",
      lookup: "warehouses",
      required: true,
    },
    {
      key: "supplierDeliveryNoteNumber",
      label: "Tedarikçi İrsaliye No",
      type: "text",
    },
    { key: "receiptDate", label: "Kabul Tarihi", type: "date", required: true },
    { key: "notes", label: "Not", type: "textarea", span: 2 },
  ],
  lineFields: [
    {
      key: "purchaseOrderLineId",
      label: "Sipariş Satırı",
      type: "select",
      lookup: "purchaseOrderLines",
      filterBy: "purchaseOrderIds",
      filterItemKey: "purchaseOrderId",
    },
    {
      key: "productId",
      label: "Ürün",
      type: "select",
      lookup: "products",
      required: true,
    },
    {
      key: "unitId",
      label: "Birim",
      type: "select",
      lookup: "units",
      required: true,
    },
    {
      key: "storageLocationId",
      label: "Hedef Raf",
      type: "select",
      lookup: "locations",
      filterBy: "warehouseId",
      filterItemKey: "warehouseId",
      required: true,
    },
    {
      key: "inventoryStatusId",
      label: "Stok Durumu",
      type: "select",
      lookup: "inventoryStatuses",
      required: true,
    },
    {
      key: "expectedQuantity",
      label: "Beklenen",
      type: "number",
      defaultValue: 1,
    },
    {
      key: "receivedQuantity",
      label: "Gelen",
      type: "number",
      defaultValue: 1,
      required: true,
    },
    {
      key: "acceptedQuantity",
      label: "Kabul",
      type: "number",
      defaultValue: 1,
      required: true,
    },
    { key: "rejectedQuantity", label: "Red", type: "number", defaultValue: 0 },
    {
      key: "unitCost",
      label: "Birim Maliyet",
      type: "number",
      defaultValue: 0,
      step: "0.01",
    },
    { key: "lotNumber", label: "Lot No", type: "text" },
    { key: "manufactureDate", label: "Üretim Tarihi", type: "date" },
    { key: "expiryDate", label: "Son Kullanma Tarihi", type: "date" },
    { key: "serialNumbers", label: "Seri Numaraları", type: "serial-entry", quantityField: "acceptedQuantity", span: 2 },
    { key: "notes", label: "Not", type: "text" },
  ],
  buildRequest: (h, l) => ({
    receiptNumber: s(h.receiptNumber) || null,
    receiptType: n(h.receiptType),
    branchId: n(h.branchId),
    supplierId: n(h.supplierId) || null,
    purchaseOrderIds: Array.isArray(h.purchaseOrderIds) ? h.purchaseOrderIds.map(Number).filter(Boolean) : [],
    tradeDossierId: n(h.tradeDossierId) || null,
    warehouseId: n(h.warehouseId),
    supplierDeliveryNoteNumber: s(h.supplierDeliveryNoteNumber) || null,
    receiptDate: s(h.receiptDate),
    notes: s(h.notes) || null,
    lines: l.map((x) => ({
      purchaseOrderLineId: n(x.purchaseOrderLineId) || null,
      productId: n(x.productId),
      unitId: n(x.unitId),
      storageLocationId: n(x.storageLocationId),
      inventoryStatusId: n(x.inventoryStatusId),
      expectedQuantity: n(x.expectedQuantity),
      receivedQuantity: n(x.receivedQuantity),
      acceptedQuantity: n(x.acceptedQuantity),
      rejectedQuantity: n(x.rejectedQuantity),
      unitCost: n(x.unitCost),
      lotNumber: s(x.lotNumber) || null,
      manufactureDate: date(x.manufactureDate),
      expiryDate: date(x.expiryDate),
      serialNumbers: s(x.serialNumbers)
        .split(/[\r\n,;\t]+/)
        .map((v) => v.trim())
        .filter(Boolean),
      notes: s(x.notes) || null,
    })),
  }),
};
export const salesForm: ErpFormConfig = {
  title: "Yeni Satış Siparişi",
  description:
    "Müşteri, teslimat, fiyat ve rezervasyon boyutlarıyla satış siparişi oluşturun.",
  endpoint: "/api/sales-orders",
  returnPath: "/sales-orders",
  submitLabel: "Satış Siparişini Oluştur",
  fields: [
    {
      key: "orderNumber",
      label: "Sipariş No (otomatik olabilir)",
      type: "text",
    },
    { key: "numberSeriesId", label: "Numara Serisi", type: "number-series", numberSeriesModule: "Sales", numberSeriesReference: "SalesOrderNumber", branchField: "branchId", warehouseField: "warehouseId" },
    {
      key: "branchId",
      label: "Şube",
      type: "select",
      lookup: "branches",
      required: true,
    },
    {
      key: "customerId",
      label: "Müşteri",
      type: "select",
      lookup: "partners",
      required: true,
    },
    {
      key: "currencyId",
      label: "Para Birimi",
      type: "select",
      lookup: "currencies",
      required: true,
    },
    {
      key: "paymentTermId",
      label: "Ödeme Koşulu",
      type: "select",
      lookup: "paymentTerms",
      required: true,
    },
    {
      key: "warehouseId",
      label: "Çıkış Deposu",
      type: "select",
      lookup: "warehouses",
      required: true,
    },
    { key: "orderDate", label: "Sipariş Tarihi", type: "date", required: true },
    { key: "requestedShipmentDate", label: "İstenen Sevk", type: "date" },
    { key: "customerReference", label: "Müşteri Referansı", type: "text" },
    {
      key: "exchangeRate",
      label: "Kur",
      type: "number",
      defaultValue: 1,
      step: "0.0001",
    },
  ],
  lineFields: [
    {
      key: "productId",
      label: "Ürün",
      type: "select",
      lookup: "products",
      required: true,
    },
    {
      key: "unitId",
      label: "Birim",
      type: "select",
      lookup: "units",
      required: true,
    },
    {
      key: "storageLocationId",
      label: "Kaynak Raf",
      type: "select",
      lookup: "locations",
      filterBy: "warehouseId",
      filterItemKey: "warehouseId",
      required: true,
    },
    {
      key: "inventoryStatusId",
      label: "Stok Durumu",
      type: "select",
      lookup: "inventoryStatuses",
      required: true,
    },
    {
      key: "quantity",
      label: "Miktar",
      type: "number",
      defaultValue: 1,
      required: true,
    },
    {
      key: "unitPrice",
      label: "Birim Fiyat (boşsa motor)",
      type: "number",
      step: "0.01",
    },
    { key: "taxRate", label: "KDV %", type: "number", defaultValue: 20 },
    { key: "inventoryLotId", label: "Lot", type: "select", lookup: "inventoryLots", filterBy: "productId", filterItemKey: "productId" },
    { key: "inventorySerialId", label: "Seri", type: "select", lookup: "inventorySerials", filterBy: "productId", filterItemKey: "productId" },
    { key: "notes", label: "Not", type: "text" },
  ],
  buildRequest: (h, l, lookups) => {
    const partner = lookups.partners?.find((x) => x.id === n(h.customerId));
    return {
      orderNumber: s(h.orderNumber) || null,
      numberSeriesId: n(h.numberSeriesId) || null,
      branchId: n(h.branchId),
      customerId: n(h.customerId),
      customerGroupId: Number(partner?.customerGroupId || 0) || null,
      currencyId: n(h.currencyId),
      paymentTermId: n(h.paymentTermId),
      warehouseId: n(h.warehouseId),
      orderDate: s(h.orderDate),
      requestedShipmentDate: date(h.requestedShipmentDate),
      customerReference: s(h.customerReference) || null,
      exchangeRate: n(h.exchangeRate) || 1,
      lines: l.map((x) => ({
        productId: n(x.productId),
        unitId: n(x.unitId),
        storageLocationId: n(x.storageLocationId),
        inventoryStatusId: n(x.inventoryStatusId),
        inventoryLotId: n(x.inventoryLotId) || null,
        inventorySerialId: n(x.inventorySerialId) || null,
        quantity: n(x.quantity),
        unitPrice: s(x.unitPrice) === "" ? null : n(x.unitPrice),
        taxRate: n(x.taxRate),
        notes: s(x.notes) || null,
      })),
    };
  },
};
export const shipmentForm: ErpFormConfig = {
  title: "Yeni Sevk",
  description: "Rezerve satış siparişinden sevk satırları oluşturun.",
  endpoint: "/api/shipments",
  returnPath: "/shipments",
  submitLabel: "Sevki Oluştur",
  fields: [
    {
      key: "shipmentNumber",
      label: "Sevk No (otomatik olabilir)",
      type: "text",
    },
    { key: "numberSeriesId", label: "Numara Serisi", type: "number-series", numberSeriesModule: "Shipping", numberSeriesReference: "ShipmentNumber" },
    {
      key: "salesOrderId",
      label: "Satış Siparişi",
      type: "select",
      lookup: "salesOrders",
      required: true,
    },
    { key: "tradeDossierId", label: "İhracat / Gümrük Dosyası", type: "select", lookup: "tradeDossiers" },
    { key: "shipmentDate", label: "Sevk Tarihi", type: "date", required: true },
    { key: "carrierName", label: "Taşıyıcı", type: "text" },
    { key: "vehiclePlate", label: "Plaka", type: "text" },
    { key: "driverName", label: "Sürücü", type: "text" },
    { key: "trackingNumber", label: "Takip No", type: "text" },
  ],
  lineFields: [
    {
      key: "salesOrderLineId",
      label: "Sipariş Satırı",
      type: "select",
      lookup: "salesOrderLines",
      filterBy: "salesOrderId",
      filterItemKey: "salesOrderId",
      required: true,
    },
    {
      key: "quantity",
      label: "Sevk Miktarı",
      type: "number",
      defaultValue: 1,
      required: true,
    },
    { key: "inventorySerialIds", label: "Sevk Edilecek Seriler", type: "serial-select", lookup: "inventorySerials", quantityField: "quantity", span: 2 },
  ],
  buildRequest: (h, l) => ({
    shipmentNumber: s(h.shipmentNumber) || null,
    numberSeriesId: n(h.numberSeriesId) || null,
    salesOrderId: n(h.salesOrderId),
    tradeDossierId: n(h.tradeDossierId) || null,
    shipmentDate: s(h.shipmentDate),
    carrierName: s(h.carrierName) || null,
    vehiclePlate: s(h.vehiclePlate) || null,
    driverName: s(h.driverName) || null,
    trackingNumber: s(h.trackingNumber) || null,
    lines: l.map((x) => ({
      salesOrderLineId: n(x.salesOrderLineId),
      quantity: n(x.quantity),
      inventorySerialIds: s(x.inventorySerialIds).split(/[\r\n,;\t]+/).map(Number).filter(Boolean),
    })),
  }),
};
export const journalForm: ErpFormConfig = {
  title: "Yeni Muhasebe Fişi",
  description: "Borç ve alacak toplamı eşit olan çift taraflı fiş oluşturun.",
  endpoint: "/api/accounting/journals",
  returnPath: "/accounting/journals",
  submitLabel: "Fişi Oluştur",
  fields: [
    { key: "journalNumber", label: "Fiş No (otomatik olabilir)", type: "text" },
    {
      key: "fiscalPeriodId",
      label: "Mali Dönem",
      type: "select",
      lookup: "fiscalPeriods",
      required: true,
    },
    { key: "postingDate", label: "Kayıt Tarihi", type: "date", required: true },
    { key: "description", label: "Açıklama", type: "textarea", span: 2 },
    {
      key: "currencyId",
      label: "Para Birimi",
      type: "select",
      lookup: "currencies",
      required: true,
    },
    { key: "exchangeRate", label: "Kur", type: "number", defaultValue: 1 },
  ],
  minimumLines: 2,
  lineFields: [
    {
      key: "ledgerAccountId",
      label: "Hesap",
      type: "select",
      lookup: "ledgerAccounts",
      required: true,
    },
    {
      key: "debit",
      label: "Borç",
      type: "number",
      defaultValue: 0,
      step: "0.01",
    },
    {
      key: "credit",
      label: "Alacak",
      type: "number",
      defaultValue: 0,
      step: "0.01",
    },
    { key: "description", label: "Açıklama", type: "text" },
  ],
  buildRequest: (h, l) => ({
    journalNumber: s(h.journalNumber) || null,
    fiscalPeriodId: n(h.fiscalPeriodId),
    postingDate: s(h.postingDate),
    sourceType: "Manual",
    sourceId: 0,
    sourceNumber: "MANUAL",
    description: s(h.description) || null,
    currencyId: n(h.currencyId),
    exchangeRate: n(h.exchangeRate) || 1,
    lines: l.map((x) => ({
      ledgerAccountId: n(x.ledgerAccountId),
      debit: n(x.debit),
      credit: n(x.credit),
      foreignDebit: 0,
      foreignCredit: 0,
      businessPartnerCode: null,
      productCode: null,
      warehouseCode: null,
      description: s(x.description) || null,
    })),
  }),
};
export const importDossierForm: ErpFormConfig = {
  title: "Yeni İthalat Dosyası",
  description: "Birden fazla satın alma ve mal kabul satırını aynı ithalat maliyet dosyasında birleştirin.",
  endpoint: "/api/import-dossiers",
  returnPath: "/import-dossiers",
  submitLabel: "İthalat Dosyasını Oluştur",
  fields: [
    { key: "dossierNumber", label: "Dosya No", type: "text", required: true },
    { key: "tradeDossierId", label: "Bağlı Dış Ticaret Dosyası", type: "select", lookup: "tradedossiers", required: true },
    { key: "branchId", label: "Şube", type: "select", lookup: "branches", required: true },
    { key: "supplierId", label: "Yurt Dışı Tedarikçi", type: "select", lookup: "partners", required: true },
    { key: "currencyId", label: "Para Birimi", type: "select", lookup: "currencies", required: true },
    { key: "incotermCode", label: "Teslim Şekli (Incoterm)", type: "text", defaultValue: "FOB", required: true },
    { key: "openDate", label: "Dosya Açılış Tarihi", type: "date", required: true },
    { key: "estimatedArrivalDate", label: "Tahmini Varış", type: "date" },
    { key: "transactionExchangeRate", label: "İşlem Kuru", type: "number", defaultValue: 1, required: true, step: "0.000001" },
    { key: "customsExchangeRate", label: "GÇB / Gümrük Kuru", type: "number", defaultValue: 1, required: true, step: "0.000001" },
    { key: "costingExchangeRate", label: "Maliyet Kuru", type: "number", defaultValue: 1, required: true, step: "0.000001" },
    { key: "notes", label: "Açıklama", type: "textarea", span: 2 },
  ],
  lineFields: [
    { key: "purchaseOrderLineId", label: "Satın Alma Sipariş Satırı", type: "select", lookup: "purchaseOrderLines" },
    { key: "productId", label: "Ürün", type: "select", lookup: "products", required: true },
    { key: "quantity", label: "Parti Miktarı", type: "number", defaultValue: 1, required: true },
    { key: "foreignUnitPrice", label: "Döviz Birim Fiyat", type: "number", defaultValue: 0, required: true, step: "0.0001" },
    { key: "netWeight", label: "Net Ağırlık", type: "number", step: "0.001" },
    { key: "grossWeight", label: "Brüt Ağırlık", type: "number", step: "0.001" },
    { key: "volume", label: "Hacim (m³/Desi)", type: "number", step: "0.001" },
    { key: "receiptTransactionId", label: "Mal Kabul Stok Hareketi", type: "select", lookup: "inventoryReceiptTransactions", filterBy: "productId", filterItemKey: "productId" },
  ],
  buildRequest: (h, l) => ({
    tradeDossierId: n(h.tradeDossierId), dossierNumber: s(h.dossierNumber), branchId: n(h.branchId), supplierId: n(h.supplierId), currencyId: n(h.currencyId), incotermCode: s(h.incotermCode), openDate: s(h.openDate), estimatedArrivalDate: date(h.estimatedArrivalDate), transactionExchangeRate: n(h.transactionExchangeRate), customsExchangeRate: n(h.customsExchangeRate), costingExchangeRate: n(h.costingExchangeRate), notes: s(h.notes) || null,
    lines: l.map((x) => ({ purchaseOrderLineId: n(x.purchaseOrderLineId) || null, goodsReceiptLineId: null, productId: n(x.productId), quantity: n(x.quantity), netWeight: s(x.netWeight) === "" ? null : n(x.netWeight), grossWeight: s(x.grossWeight) === "" ? null : n(x.grossWeight), volume: s(x.volume) === "" ? null : n(x.volume), foreignUnitPrice: n(x.foreignUnitPrice), transactionExchangeRate: null, customsExchangeRate: null, costingExchangeRate: null, receiptTransactionId: n(x.receiptTransactionId) || null })),
  }),
};
export const landedCostTypeForm: ErpFormConfig = {
  title: "Yeni İthalat Masraf Türü", description: "Varsayılan dağıtım anahtarını ve muhasebe hesaplarını belirleyin.", endpoint: "/api/import-dossiers/cost-types", returnPath: "/import-dossiers/definitions/cost-types", submitLabel: "Masraf Türünü Oluştur",
  fields: [
    {key:"code",label:"Masraf Kodu",type:"text",required:true},{key:"name",label:"Masraf Adı",type:"text",required:true},{key:"description",label:"Açıklama",type:"textarea",span:2},
    {key:"defaultAllocationMethod",label:"Dağıtım Yöntemi (1:Tutar, 2:Miktar, 3:Ağırlık, 4:Hacim, 5:Eşit, 6:Manuel)",type:"number",defaultValue:1,required:true},
    {key:"clearingAccountId",label:"Mahsup / Clearing Hesabı",type:"select",lookup:"ledgerAccounts"},{key:"varianceAccountId",label:"Maliyet Fark Hesabı",type:"select",lookup:"ledgerAccounts"},
    {key:"includeInCustomsValue",label:"Gümrük Kıymetine Dahil",type:"checkbox"},{key:"capitalizeToInventory",label:"Stok Maliyetine Ekle",type:"checkbox",defaultValue:true},{key:"isDefault",label:"Varsayılan",type:"checkbox"},{key:"isActive",label:"Aktif",type:"checkbox",defaultValue:true},{key:"displayOrder",label:"Sıra",type:"number",defaultValue:10}
  ],
  buildRequest:(h)=>({code:s(h.code),name:s(h.name),description:s(h.description)||null,defaultAllocationMethod:n(h.defaultAllocationMethod),includeInCustomsValue:b(h.includeInCustomsValue),capitalizeToInventory:b(h.capitalizeToInventory),clearingAccountId:n(h.clearingAccountId)||null,varianceAccountId:n(h.varianceAccountId)||null,isActive:b(h.isActive),isDefault:b(h.isDefault),displayOrder:n(h.displayOrder)})
};
export const tradeDossierForm: ErpFormConfig = {
 title:"Yeni Dış Ticaret Dosyası",description:"İthalat veya ihracat operasyonunu; cari, teslim şekli, gümrük ve antrepo bilgileriyle açın.",endpoint:"/api/trade-dossiers",returnPath:"/trade-dossiers",submitLabel:"Dosyayı Oluştur",
 fields:[
  {key:"dossierNumber",label:"Dosya Numarası",type:"text",required:true},
  {key:"direction",label:"Ticaret Yönü",type:"select",required:true,defaultValue:1,options:[{id:1,code:"IMPORT",name:"İthalat"},{id:2,code:"EXPORT",name:"İhracat"}]},
  {key:"operationType",label:"Operasyon Türü",type:"select",required:true,defaultValue:1,options:[{id:1,code:"DEFINITIVE",name:"Kesin İthalat / İhracat"},{id:2,code:"TEMPORARY",name:"Geçici"},{id:3,code:"INWARD_PROCESSING",name:"Dahilde İşleme"},{id:4,code:"RETURN",name:"İade"},{id:5,code:"RE_EXPORT",name:"Yeniden İhracat"}]},
  {key:"branchId",label:"Şube",type:"select",lookup:"branches",required:true},{key:"businessPartnerId",label:"İlgili Cari",type:"select",lookup:"partners",required:true},
  {key:"customsBrokerId",label:"Gümrük Müşaviri",type:"select",lookup:"partners"},{key:"carrierId",label:"Taşıyıcı",type:"select",lookup:"partners"},
  {key:"currencyId",label:"Para Birimi",type:"select",lookup:"currencies",required:true},{key:"incotermCode",label:"Teslim Şekli (Incoterm)",type:"text",defaultValue:"FOB",required:true},
  {key:"paymentMethodCode",label:"Ödeme Şekli",type:"text"},{key:"deliveryMethodCode",label:"Taşıma / Teslim Yöntemi",type:"text"},{key:"customsOfficeCode",label:"Gümrük İdaresi Kodu",type:"text"},{key:"bondedWarehouseId",label:"Antrepo / Gümrük Deposu",type:"select",lookup:"warehouses"},
  {key:"transportMode",label:"Taşıma Modu",type:"select",required:true,defaultValue:1,options:[{id:1,code:"ROAD",name:"Karayolu"},{id:2,code:"SEA",name:"Denizyolu"},{id:3,code:"AIR",name:"Havayolu"},{id:4,code:"RAIL",name:"Demiryolu"},{id:5,code:"MULTIMODAL",name:"Multimodal"},{id:6,code:"COURIER",name:"Hızlı Kargo"}]},
  {key:"masterTransportDocumentNumber",label:"Ana Taşıma Belgesi / Konşimento",type:"text"},{key:"houseTransportDocumentNumber",label:"Ara Taşıma Belgesi",type:"text"},{key:"containerNumber",label:"Konteyner Numarası",type:"text"},{key:"vehicleOrVoyageNumber",label:"Plaka / Sefer / Uçuş Numarası",type:"text"},
  {key:"portOfLoadingCode",label:"Yükleme Limanı Kodu",type:"text"},{key:"portOfDischargeCode",label:"Boşaltma Limanı Kodu",type:"text"},{key:"countryOfDispatchCode",label:"Sevk Ülkesi",type:"text"},
  {key:"openDate",label:"Dosya Açılış Tarihi",type:"date",required:true},{key:"estimatedArrivalDate",label:"Tahmini Varış Tarihi",type:"date"},{key:"notes",label:"Açıklama",type:"textarea",span:2}
 ],
 buildRequest:(h)=>({dossierNumber:s(h.dossierNumber),direction:n(h.direction),operationType:n(h.operationType),branchId:n(h.branchId),businessPartnerId:n(h.businessPartnerId),customsBrokerId:n(h.customsBrokerId)||null,carrierId:n(h.carrierId)||null,currencyId:n(h.currencyId),incotermCode:s(h.incotermCode),paymentMethodCode:s(h.paymentMethodCode)||null,deliveryMethodCode:s(h.deliveryMethodCode)||null,customsOfficeCode:s(h.customsOfficeCode)||null,bondedWarehouseId:n(h.bondedWarehouseId)||null,transportMode:n(h.transportMode),masterTransportDocumentNumber:s(h.masterTransportDocumentNumber)||null,houseTransportDocumentNumber:s(h.houseTransportDocumentNumber)||null,containerNumber:s(h.containerNumber)||null,vehicleOrVoyageNumber:s(h.vehicleOrVoyageNumber)||null,portOfLoadingCode:s(h.portOfLoadingCode)||null,portOfDischargeCode:s(h.portOfDischargeCode)||null,countryOfDispatchCode:s(h.countryOfDispatchCode)||null,openDate:s(h.openDate),estimatedArrivalDate:date(h.estimatedArrivalDate),notes:s(h.notes)||null})
};
