import{useEffect,useState,type FormEvent,type ReactElement,type ReactNode}from'react';
import{useQuery,useQueryClient}from'@tanstack/react-query';
import{useTranslation}from'react-i18next';
import{CheckCircle2,Clock3,FileCheck2,Link2,Save,ShieldCheck}from'lucide-react';
import{toast}from'sonner';
import{api}from'@/lib/axios';
import{useAuthStore}from'@/stores/auth-store';
import{Button}from'@/components/ui/button';
import{Input}from'@/components/ui/input';
import{Label}from'@/components/ui/label';
import{ErpLookupCombobox}from'@/features/erp-form-management/ErpLookupCombobox';

type Envelope<T>={data:T};
type Parameters={branchId:number;providerType:number;providerEnvironment:string;invoiceServiceUrl:string;despatchServiceUrl:string;credentialReference:string;timeoutSeconds:number;maximumRetryCount:number;providerIsActive:boolean;defaultInvoiceScenario:string;defaultArchiveInvoiceScenario:string;defaultDespatchScenario:string;autoQueueAfterCreate:boolean;requireUblValidation:boolean;requireCompanyLegalProfile:boolean;requireTaxNumberValidation:boolean;preventDuplicateSourceDocument:boolean;fallbackToEArchive:boolean;requireRecipientMailboxForEInvoice:boolean;sendEArchiveByEmail:boolean;allowManualScenario:boolean;retryDelayMinutes:number;statusPollingIntervalMinutes:number;archiveRetentionYears:number;maximumXmlSizeKb:number;defaultCurrencyId:number;defaultCurrencyCode:string};
const titles:Record<string,[string,string,string]>={tr:['E-İrsaliye ve E-Fatura Parametreleri','E-Belge Yönetimi','CRS Soft bağlantısı, belge senaryoları, doğrulama, kuyruk ve saklama kurallarını yönetin.'],en:['E-Dispatch and E-Invoice Parameters','E-Document Management','Manage CRS Soft connection, document scenarios, validation, queue and retention rules.'],de:['E-Lieferschein- und E-Rechnungsparameter','E-Dokumentverwaltung','CRS-Soft-Verbindung, Szenarien, Validierung, Warteschlange und Aufbewahrung verwalten.'],fr:['Paramètres e-Despatch et e-Facture','Gestion des e-documents','Gérez la connexion CRS Soft, les scénarios, la validation, la file et la conservation.'],es:['Parámetros de e-Despacho y e-Factura','Gestión de documentos electrónicos','Gestione CRS Soft, escenarios, validación, cola y conservación.'],it:['Parametri e-DDT ed e-Fattura','Gestione documenti elettronici','Gestisci CRS Soft, scenari, convalida, coda e conservazione.'],pt:['Parâmetros de e-Expedição e e-Fatura','Gestão de documentos eletrônicos','Gerencie CRS Soft, cenários, validação, fila e retenção.'],nl:['E-verzend- en e-factuurparameters','E-documentbeheer','Beheer CRS Soft, scenario’s, validatie, wachtrij en bewaring.'],pl:['Parametry e-WZ i e-Faktury','Zarządzanie e-dokumentami','Zarządzaj CRS Soft, scenariuszami, walidacją, kolejką i retencją.'],ru:['Параметры э-накладной и э-счёта','Управление э-документами','Управляйте CRS Soft, сценариями, проверкой, очередью и хранением.'],ar:['معلمات الإرسالية والفاتورة الإلكترونية','إدارة المستندات الإلكترونية','إدارة اتصال CRS Soft والسيناريوهات والتحقق وقائمة الانتظار والحفظ.'],fa:['پارامترهای حواله و فاکتور الکترونیکی','مدیریت اسناد الکترونیکی','اتصال CRS Soft، سناریوها، اعتبارسنجی، صف و نگهداری را مدیریت کنید.'],ja:['電子出荷・電子請求書パラメータ','電子文書管理','CRS Soft 接続、シナリオ、検証、キュー、保存を管理します。'],ko:['전자 발송 및 전자 송장 매개변수','전자 문서 관리','CRS Soft 연결, 시나리오, 검증, 대기열 및 보존을 관리합니다.'],zh:['电子发货单与电子发票参数','电子文档管理','管理 CRS Soft 连接、场景、验证、队列和保留规则。']};

export function EDocumentParametersPage():ReactElement{
 const{t:te,i18n}=useTranslation('erp');const{t:tc}=useTranslation('common');const tx=titles[i18n.language.split('-')[0]]??titles.en;const branch=useAuthStore(s=>s.branch);const branchId=Number(branch?.id??0);const[saving,setSaving]=useState(false);const client=useQueryClient();
 const query=useQuery({queryKey:['e-document-parameters',branchId],enabled:branchId>0,queryFn:async()=>{const r=await api.get<Envelope<Parameters>>('/api/parameters/e-documents',{params:{branchId}});return r.data}});const[form,setForm]=useState<Parameters|null>(null);useEffect(()=>{if(query.data)setForm({...query.data,branchId})},[query.data,branchId]);const set=<K extends keyof Parameters>(k:K,v:Parameters[K])=>setForm(x=>x?{...x,[k]:v}:x);
 const submit=async(e:FormEvent)=>{e.preventDefault();if(!form)return;try{setSaving(true);const r=await api.put<Envelope<Parameters>>('/api/parameters/e-documents',{...form,branchId});setForm(r.data);await client.invalidateQueries({queryKey:['e-document-parameters']});toast.success(te('eDocumentParameters.saved',{defaultValue:'E-belge parametreleri kaydedildi.'}))}catch(error){toast.error(error instanceof Error?error.message:'Parametreler kaydedilemedi.')}finally{setSaving(false)}};
 if(branchId<=0)return<div className="metivon-panel rounded-3xl p-8">Parametreleri yönetmek için aktif şube seçin.</div>;if(query.isLoading||!form)return<div className="metivon-panel rounded-3xl p-8">...</div>;if(query.isError)return<div className="rounded-3xl border border-red-300 bg-red-50 p-6 text-red-700">E-belge parametreleri yüklenemedi.</div>;
 return<form onSubmit={submit}className="space-y-5"><section className="metivon-hero rounded-3xl p-6 md:p-8"><div className="flex flex-col gap-5 md:flex-row md:items-end md:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.24em] text-white/65">{tx[1]}</p><h1 className="mt-2 text-3xl font-semibold">{tx[0]}</h1><p className="mt-2 max-w-3xl text-white/75">{tx[2]}</p></div><Button type="submit"className="bg-white text-violet-950 hover:bg-white/90"disabled={saving}><Save/>{saving?tc('common.saving'):tc('common.save')}</Button></div></section>
 <div className="grid gap-5 xl:grid-cols-2"><Panel icon={<Link2/>}title="CRS Soft entegratör bağlantısı"><div className="grid gap-4 sm:grid-cols-2"><Field label="Şube"><Input value={branch?.name??String(branchId)}disabled/></Field><Field label="Entegratör"><Input value="CRS Soft"disabled/></Field><Field label="Ortam"wide><div className="grid grid-cols-2 gap-2"><Choice active={form.providerEnvironment==='Test'}onClick={()=>set('providerEnvironment','Test')}>Test</Choice><Choice active={form.providerEnvironment==='Production'}onClick={()=>set('providerEnvironment','Production')}>Canlı</Choice></div></Field><Field label="Fatura servis adresi"wide><Input value={form.invoiceServiceUrl}placeholder="https://..."onChange={e=>set('invoiceServiceUrl',e.target.value)}/></Field><Field label="İrsaliye servis adresi"wide><Input value={form.despatchServiceUrl}placeholder="https://..."onChange={e=>set('despatchServiceUrl',e.target.value)}/></Field><Field label="Kimlik bilgisi referansı"wide><Input value={form.credentialReference}placeholder="Secret vault / configuration key"onChange={e=>set('credentialReference',e.target.value)}/></Field><Num label="Zaman aşımı (sn)"value={form.timeoutSeconds}min={5}max={300}onChange={v=>set('timeoutSeconds',v)}/><Num label="Maksimum tekrar"value={form.maximumRetryCount}max={20}onChange={v=>set('maximumRetryCount',v)}/><Toggle label="Entegratör bağlantısı aktif"checked={form.providerIsActive}onChange={v=>set('providerIsActive',v)}/></div></Panel>
 <Panel icon={<FileCheck2/>}title="Belge senaryoları"><div className="grid gap-4 sm:grid-cols-2"><Field label="E-Fatura senaryosu"><Input value={form.defaultInvoiceScenario}onChange={e=>set('defaultInvoiceScenario',e.target.value.toUpperCase())}/></Field><Field label="E-Arşiv senaryosu"><Input value={form.defaultArchiveInvoiceScenario}onChange={e=>set('defaultArchiveInvoiceScenario',e.target.value.toUpperCase())}/></Field><Field label="E-İrsaliye senaryosu"><Input value={form.defaultDespatchScenario}onChange={e=>set('defaultDespatchScenario',e.target.value.toUpperCase())}/></Field><Field label="Varsayılan para birimi"><ErpLookupCombobox lookupKey="currencies" value={String(form.defaultCurrencyId||'')} fallbackOptions={[]} placeholder="Para birimi seçin" searchPlaceholder="Para birimlerinde ara..." onChange={value=>set('defaultCurrencyId',Number(value)||0)}/></Field><Toggle label="Manuel senaryo seçimine izin ver"checked={form.allowManualScenario}onChange={v=>set('allowManualScenario',v)}/><Toggle label="Mükellef değilse E-Arşiv'e dön"checked={form.fallbackToEArchive}onChange={v=>set('fallbackToEArchive',v)}/><Toggle label="E-Arşivi e-posta ile gönder"checked={form.sendEArchiveByEmail}onChange={v=>set('sendEArchiveByEmail',v)}/></div></Panel></div>
 <div className="grid gap-5 xl:grid-cols-2"><Panel icon={<ShieldCheck/>}title="Doğrulama ve güvenlik"><div className="grid gap-3 sm:grid-cols-2"><Toggle label="UBL doğrulaması zorunlu"checked={form.requireUblValidation}onChange={v=>set('requireUblValidation',v)}/><Toggle label="Firma yasal profili zorunlu"checked={form.requireCompanyLegalProfile}onChange={v=>set('requireCompanyLegalProfile',v)}/><Toggle label="VKN/TCKN doğrulaması zorunlu"checked={form.requireTaxNumberValidation}onChange={v=>set('requireTaxNumberValidation',v)}/><Toggle label="Kaynak belge tekrarını engelle"checked={form.preventDuplicateSourceDocument}onChange={v=>set('preventDuplicateSourceDocument',v)}/><Toggle label="E-Faturada alıcı posta kutusu zorunlu"checked={form.requireRecipientMailboxForEInvoice}onChange={v=>set('requireRecipientMailboxForEInvoice',v)}/><Num label="Maksimum XML boyutu (KB)"value={form.maximumXmlSizeKb}min={64}max={10240}onChange={v=>set('maximumXmlSizeKb',v)}/></div></Panel>
 <Panel icon={<Clock3/>}title="Kuyruk ve saklama"><div className="grid gap-3 sm:grid-cols-2"><Toggle label="Oluşturunca otomatik kuyruğa al"checked={form.autoQueueAfterCreate}onChange={v=>set('autoQueueAfterCreate',v)}/><Num label="Tekrar bekleme süresi (dk)"value={form.retryDelayMinutes}min={1}max={1440}onChange={v=>set('retryDelayMinutes',v)}/><Num label="Durum sorgulama aralığı (dk)"value={form.statusPollingIntervalMinutes}min={1}max={1440}onChange={v=>set('statusPollingIntervalMinutes',v)}/><Num label="Arşiv saklama süresi (yıl)"value={form.archiveRetentionYears}min={1}max={20}onChange={v=>set('archiveRetentionYears',v)}/></div></Panel></div></form>;
}
function Panel({icon,title,children}:{icon:ReactElement;title:string;children:ReactNode}){return<section className="metivon-panel rounded-3xl border p-5 md:p-6"><div className="mb-5 flex items-center gap-3 text-lg font-semibold"><span className="metivon-brand-soft grid h-10 w-10 place-items-center rounded-xl">{icon}</span>{title}</div>{children}</section>}
function Toggle({label,checked,onChange}:{label:string;checked:boolean;onChange:(v:boolean)=>void}){return<label className="flex min-h-16 cursor-pointer items-center gap-3 rounded-2xl border p-4"><input type="checkbox"className="h-4 w-4"checked={checked}onChange={e=>onChange(e.target.checked)}/><CheckCircle2 className={`h-4 w-4 ${checked?'text-[var(--crm-brand-primary)]':'text-muted-foreground'}`}/><span className="font-semibold">{label}</span></label>}
function Field({label,children,wide}:{label:string;children:ReactNode;wide?:boolean}){return<div className={`space-y-2 ${wide?'sm:col-span-2':''}`}><Label>{label}</Label>{children}</div>}
function Num({label,value,onChange,min=0,max}:{label:string;value:number;onChange:(v:number)=>void;min?:number;max?:number}){return<Field label={label}><Input type="number"min={min}max={max}value={value}onChange={e=>onChange(Number(e.target.value))}/></Field>}
function Choice({active,onClick,children}:{active:boolean;onClick:()=>void;children:ReactNode}){return<button type="button"onClick={onClick}className={`rounded-xl border px-4 py-2 text-sm font-semibold transition ${active?'metivon-brand-soft border-[var(--crm-brand-primary)]':'hover:bg-muted'}`}>{children}</button>}
