import{useEffect,useState,type FormEvent,type ReactElement,type ReactNode}from'react';
import{useQuery,useQueryClient}from'@tanstack/react-query';
import{useTranslation}from'react-i18next';
import{Barcode,CalendarClock,CheckCircle2,PackageCheck,Save,ShieldCheck,Warehouse}from'lucide-react';
import{toast}from'sonner';
import{api}from'@/lib/axios';
import{useAuthStore}from'@/stores/auth-store';
import{Button}from'@/components/ui/button';
import{Input}from'@/components/ui/input';
import{Label}from'@/components/ui/label';
import{ErpLookupCombobox}from'@/features/erp-form-management/ErpLookupCombobox';

type Envelope<T>={data:T};
type Parameters={branchId:number|null;warehouseId:number|null;requireLotForLotTrackedProducts:boolean;requireSerialForSerialTrackedProducts:boolean;requireExpiryDateForShelfLifeProducts:boolean;requireManufactureDateWhenExpiryExists:boolean;rejectExpiredReceipts:boolean;minimumRemainingShelfLifeDays:number;minimumRemainingShelfLifePercent:number;preventDuplicateSerialNumbers:boolean;blockExpiredShipments:boolean;enforceFefoOnShipments:boolean;expiryWarningDays:number;allowMixedLotsPerDocument:boolean;autoCreateLabelsAfterReceipt:boolean;defaultLabelCopies:number};
const titles:Record<string,[string,string,string,string,string]>={tr:['Lot, Seri ve SKT Parametreleri','Stok Yönetimi','Ürün izlenebilirliği, raf ömrü, FEFO ve etiket kurallarını yönetin.','Tüm depolar','Depo ara...'],en:['Lot, Serial and Expiry Parameters','Inventory Management','Manage product traceability, shelf life, FEFO and label rules.','All warehouses','Search warehouse...'],de:['Chargen-, Serien- und Ablaufparameter','Bestandsverwaltung','Rückverfolgbarkeit, Haltbarkeit, FEFO und Etiketten verwalten.','Alle Lager','Lager suchen...'],fr:['Paramètres de lot, série et péremption','Gestion des stocks','Gérez la traçabilité, la durée de vie, FEFO et les étiquettes.','Tous les entrepôts','Rechercher un entrepôt...'],es:['Parámetros de lote, serie y caducidad','Gestión de inventario','Gestione trazabilidad, vida útil, FEFO y etiquetas.','Todos los almacenes','Buscar almacén...'],it:['Parametri lotto, serie e scadenza','Gestione scorte','Gestisci tracciabilità, durata, FEFO ed etichette.','Tutti i magazzini','Cerca magazzino...'],pt:['Parâmetros de lote, série e validade','Gestão de estoque','Gerencie rastreabilidade, validade, FEFO e etiquetas.','Todos os armazéns','Pesquisar armazém...'],nl:['Partij-, serie- en vervalparameters','Voorraadbeheer','Beheer traceerbaarheid, houdbaarheid, FEFO en labels.','Alle magazijnen','Magazijn zoeken...'],pl:['Parametry partii, serii i ważności','Zarządzanie zapasami','Zarządzaj identyfikowalnością, trwałością, FEFO i etykietami.','Wszystkie magazyny','Szukaj magazynu...'],ru:['Параметры партий, серий и сроков','Управление запасами','Управляйте прослеживаемостью, сроком годности, FEFO и этикетками.','Все склады','Поиск склада...'],ar:['معلمات الدفعة والرقم التسلسلي والصلاحية','إدارة المخزون','إدارة التتبع ومدة الصلاحية وFEFO والملصقات.','جميع المستودعات','البحث عن مستودع...'],fa:['پارامترهای بچ، سریال و انقضا','مدیریت موجودی','ردیابی، عمر مفید، FEFO و برچسب‌ها را مدیریت کنید.','همه انبارها','جستجوی انبار...'],ja:['ロット・シリアル・有効期限パラメータ','在庫管理','トレーサビリティ、保存期間、FEFO、ラベルを管理します。','すべての倉庫','倉庫を検索...'],ko:['로트, 일련번호 및 유효기간 매개변수','재고 관리','추적성, 유통기한, FEFO 및 라벨 규칙을 관리합니다.','모든 창고','창고 검색...'],zh:['批次、序列号和有效期参数','库存管理','管理产品追溯、保质期、FEFO 和标签规则。','所有仓库','搜索仓库...']};

export function InventoryTraceabilityParametersPage():ReactElement{
 const{t:te,i18n}=useTranslation('erp');const{t:tc}=useTranslation('common');const tx=titles[i18n.language.split('-')[0]]??titles.en;const branch=useAuthStore(s=>s.branch);const branchId=Number(branch?.id??0)||null;const[warehouseId,setWarehouseId]=useState<number|null>(null);const[saving,setSaving]=useState(false);const client=useQueryClient();
 const query=useQuery({queryKey:['inventory-traceability-parameters',branchId,warehouseId],queryFn:async()=>{const r=await api.get<Envelope<Parameters>>('/api/parameters/inventory-traceability',{params:{branchId,warehouseId}});return r.data}});const[form,setForm]=useState<Parameters|null>(null);useEffect(()=>{if(query.data)setForm({...query.data,branchId,warehouseId})},[query.data,branchId,warehouseId]);const set=<K extends keyof Parameters>(k:K,v:Parameters[K])=>setForm(x=>x?{...x,[k]:v}:x);
 const submit=async(e:FormEvent)=>{e.preventDefault();if(!form)return;try{setSaving(true);const r=await api.put<Envelope<Parameters>>('/api/parameters/inventory-traceability',{...form,branchId,warehouseId});setForm(r.data);await client.invalidateQueries({queryKey:['inventory-traceability-parameters']});toast.success(te('traceabilityParameters.saved',{defaultValue:'İzlenebilirlik parametreleri kaydedildi.'}))}catch(error){toast.error(error instanceof Error?error.message:'Parametreler kaydedilemedi.')}finally{setSaving(false)}};
 if(query.isLoading||!form)return<div className="metivon-panel rounded-3xl p-8">...</div>;if(query.isError)return<div className="rounded-3xl border border-red-300 bg-red-50 p-6 text-red-700">İzlenebilirlik parametreleri yüklenemedi.</div>;
 return<form onSubmit={submit}className="space-y-5"><section className="metivon-hero rounded-3xl p-6 md:p-8"><div className="flex flex-col gap-5 md:flex-row md:items-end md:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.24em] text-white/65">{tx[1]}</p><h1 className="mt-2 text-3xl font-semibold">{tx[0]}</h1><p className="mt-2 max-w-3xl text-white/75">{tx[2]}</p></div><Button type="submit"className="bg-white text-violet-950 hover:bg-white/90"disabled={saving}><Save/>{saving?tc('common.saving'):tc('common.save')}</Button></div></section>
 <div className="grid gap-5 xl:grid-cols-3"><Panel icon={<Warehouse/>}title="Parametre kapsamı"><p className="text-sm text-muted-foreground">{branch?.name??'-'}</p><div className="mt-4"><Label>Depo</Label><div className="mt-2"><ErpLookupCombobox lookupKey="warehouses"value={String(warehouseId??'')}fallbackOptions={[]}placeholder={tx[3]}searchPlaceholder={tx[4]}onChange={v=>setWarehouseId(v===''?null:v)}/></div></div></Panel>
 <Panel icon={<Barcode/>}title="Lot ve seri izlenebilirliği"><div className="grid gap-3 sm:grid-cols-2"><Toggle label="Lot takipli üründe lot zorunlu"checked={form.requireLotForLotTrackedProducts}onChange={v=>set('requireLotForLotTrackedProducts',v)}/><Toggle label="Seri takipli üründe seri zorunlu"checked={form.requireSerialForSerialTrackedProducts}onChange={v=>set('requireSerialForSerialTrackedProducts',v)}/><Toggle label="Tekrarlanan seri numarasını engelle"checked={form.preventDuplicateSerialNumbers}onChange={v=>set('preventDuplicateSerialNumbers',v)}/><Toggle label="Belgede karışık lot kullanımına izin ver"checked={form.allowMixedLotsPerDocument}onChange={v=>set('allowMixedLotsPerDocument',v)}/></div></Panel>
 <Panel icon={<CalendarClock/>}title="Raf ömrü ve SKT"><div className="grid gap-3 sm:grid-cols-2"><Toggle label="Raf ömürlü üründe SKT zorunlu"checked={form.requireExpiryDateForShelfLifeProducts}onChange={v=>set('requireExpiryDateForShelfLifeProducts',v)}/><Toggle label="SKT varsa üretim tarihi zorunlu"checked={form.requireManufactureDateWhenExpiryExists}onChange={v=>set('requireManufactureDateWhenExpiryExists',v)}/><Toggle label="Süresi geçmiş mal kabulü engelle"checked={form.rejectExpiredReceipts}onChange={v=>set('rejectExpiredReceipts',v)}/><Num label="Minimum kalan raf ömrü (gün)"value={form.minimumRemainingShelfLifeDays}onChange={v=>set('minimumRemainingShelfLifeDays',v)}/><Num label="Minimum kalan raf ömrü (%)"value={form.minimumRemainingShelfLifePercent}max={100}onChange={v=>set('minimumRemainingShelfLifePercent',v)}/><Num label="SKT uyarı süresi (gün)"value={form.expiryWarningDays}onChange={v=>set('expiryWarningDays',v)}/></div></Panel></div>
 <div className="grid gap-5 xl:grid-cols-2"><Panel icon={<ShieldCheck/>}title="Sevkiyat kuralları"><div className="grid gap-3 sm:grid-cols-2"><Toggle label="Süresi geçmiş lot sevkiyatını engelle"checked={form.blockExpiredShipments}onChange={v=>set('blockExpiredShipments',v)}/><Toggle label="FEFO sırasını zorunlu uygula"checked={form.enforceFefoOnShipments}onChange={v=>set('enforceFefoOnShipments',v)}/></div></Panel><Panel icon={<PackageCheck/>}title="Etiketleme"><div className="grid gap-3 sm:grid-cols-2"><Toggle label="Mal kabul sonrası etiketi hazırla"checked={form.autoCreateLabelsAfterReceipt}onChange={v=>set('autoCreateLabelsAfterReceipt',v)}/><Num label="Varsayılan etiket kopyası"value={form.defaultLabelCopies}min={1}max={100}onChange={v=>set('defaultLabelCopies',v)}/></div></Panel></div></form>;
}
function Panel({icon,title,children}:{icon:ReactElement;title:string;children:ReactNode}){return<section className="metivon-panel rounded-3xl border p-5 md:p-6"><div className="mb-5 flex items-center gap-3 text-lg font-semibold"><span className="metivon-brand-soft grid h-10 w-10 place-items-center rounded-xl">{icon}</span>{title}</div>{children}</section>}
function Toggle({label,checked,onChange}:{label:string;checked:boolean;onChange:(v:boolean)=>void}){return<label className="flex min-h-16 cursor-pointer items-center gap-3 rounded-2xl border p-4"><input type="checkbox"className="h-4 w-4"checked={checked}onChange={e=>onChange(e.target.checked)}/><CheckCircle2 className={`h-4 w-4 ${checked?'text-[var(--crm-brand-primary)]':'text-muted-foreground'}`}/><span className="font-semibold">{label}</span></label>}
function Num({label,value,onChange,min=0,max}:{label:string;value:number;onChange:(v:number)=>void;min?:number;max?:number}){return<div className="space-y-2"><Label>{label}</Label><Input type="number"min={min}max={max}value={value}onChange={e=>onChange(Number(e.target.value))}/></div>}
