import { useMemo, type ReactElement } from "react";
import { useQuery } from "@tanstack/react-query";
import { Link } from "react-router-dom";
import { useTranslation } from "react-i18next";
import { AlertTriangle, ArrowRight, Boxes, CalendarClock, History, PackageCheck, RefreshCw, ShieldCheck, Warehouse } from "lucide-react";
import { api } from "@/lib/axios";
import { Button } from "@/components/ui/button";
import { useAuthStore } from "@/stores/auth-store";
import { formatSystemAmount, formatSystemCurrency, formatSystemDateTime } from "@/lib/system-settings";

type DashboardCopy={eyebrow:string;title:string;description:string;refreshed:string;retry:string;physical:string;available:string;reserved:string;value:string;products:string;dimensions:string;exceptions:string;lowStock:string;expiring:string;negative:string;warehouses:string;statuses:string;recent:string;empty:string;loadError:string};
const copy:Record<string,DashboardCopy>={
tr:{eyebrow:"Stok 360",title:"Stok kontrol merkezi",description:"Miktar, değer, kullanılabilirlik, depo dağılımı ve kritik istisnaları tek ekrandan yönetin.",refreshed:"Son hesaplama",retry:"Yeniden dene",physical:"Fiziksel stok",available:"Kullanılabilir",reserved:"Rezerve",value:"Stok değeri",products:"Stoklu ürün",dimensions:"Stok boyutu",exceptions:"Operasyonel istisnalar",lowStock:"Sipariş noktasının altında",expiring:"Yaklaşan SKT",negative:"Negatif bakiye",warehouses:"Depo dağılımı",statuses:"Stok durumları",recent:"Son stok hareketleri",empty:"Henüz stok hareketi yok.",loadError:"Stok özeti yüklenemedi."},
en:{eyebrow:"Inventory 360",title:"Inventory control center",description:"Manage quantity, value, availability, warehouse distribution and critical exceptions in one place.",refreshed:"Last calculated",retry:"Try again",physical:"Physical stock",available:"Available",reserved:"Reserved",value:"Inventory value",products:"Stocked products",dimensions:"Inventory dimensions",exceptions:"Operational exceptions",lowStock:"Below reorder point",expiring:"Expiring soon",negative:"Negative balances",warehouses:"Warehouse distribution",statuses:"Inventory statuses",recent:"Recent inventory movements",empty:"No inventory movement yet.",loadError:"Inventory overview could not be loaded."},
de:{eyebrow:"Bestand 360",title:"Bestandskontrollzentrum",description:"Menge, Wert, Verfügbarkeit, Lagerverteilung und kritische Ausnahmen zentral steuern.",refreshed:"Zuletzt berechnet",retry:"Erneut versuchen",physical:"Physischer Bestand",available:"Verfügbar",reserved:"Reserviert",value:"Bestandswert",products:"Lagerartikel",dimensions:"Bestandsdimensionen",exceptions:"Betriebliche Ausnahmen",lowStock:"Unter Meldebestand",expiring:"Bald ablaufend",negative:"Negative Bestände",warehouses:"Lagerverteilung",statuses:"Bestandsstatus",recent:"Letzte Bestandsbewegungen",empty:"Noch keine Bestandsbewegung.",loadError:"Bestandsübersicht konnte nicht geladen werden."},
fr:{eyebrow:"Stock 360",title:"Centre de contrôle des stocks",description:"Gérez quantité, valeur, disponibilité, répartition par entrepôt et exceptions critiques au même endroit.",refreshed:"Dernier calcul",retry:"Réessayer",physical:"Stock physique",available:"Disponible",reserved:"Réservé",value:"Valeur du stock",products:"Produits stockés",dimensions:"Dimensions de stock",exceptions:"Exceptions opérationnelles",lowStock:"Sous le point de commande",expiring:"Expiration proche",negative:"Soldes négatifs",warehouses:"Répartition des entrepôts",statuses:"Statuts de stock",recent:"Mouvements récents",empty:"Aucun mouvement de stock.",loadError:"Impossible de charger la vue des stocks."},
es:{eyebrow:"Inventario 360",title:"Centro de control de inventario",description:"Gestione cantidad, valor, disponibilidad, distribución por almacén y excepciones críticas en un solo lugar.",refreshed:"Último cálculo",retry:"Reintentar",physical:"Stock físico",available:"Disponible",reserved:"Reservado",value:"Valor de inventario",products:"Productos en stock",dimensions:"Dimensiones de inventario",exceptions:"Excepciones operativas",lowStock:"Bajo punto de pedido",expiring:"Próximo a caducar",negative:"Saldos negativos",warehouses:"Distribución de almacenes",statuses:"Estados de inventario",recent:"Movimientos recientes",empty:"Aún no hay movimientos.",loadError:"No se pudo cargar el resumen."},
it:{eyebrow:"Inventario 360",title:"Centro controllo inventario",description:"Gestisci quantità, valore, disponibilità, distribuzione magazzini ed eccezioni critiche in un unico punto.",refreshed:"Ultimo calcolo",retry:"Riprova",physical:"Scorta fisica",available:"Disponibile",reserved:"Riservato",value:"Valore inventario",products:"Prodotti a stock",dimensions:"Dimensioni inventario",exceptions:"Eccezioni operative",lowStock:"Sotto punto di riordino",expiring:"In scadenza",negative:"Saldi negativi",warehouses:"Distribuzione magazzini",statuses:"Stati inventario",recent:"Movimenti recenti",empty:"Nessun movimento inventario.",loadError:"Impossibile caricare il riepilogo."},
pt:{eyebrow:"Estoque 360",title:"Centro de controle de estoque",description:"Gerencie quantidade, valor, disponibilidade, distribuição por armazém e exceções críticas em um só lugar.",refreshed:"Último cálculo",retry:"Tentar novamente",physical:"Estoque físico",available:"Disponível",reserved:"Reservado",value:"Valor do estoque",products:"Produtos em estoque",dimensions:"Dimensões de estoque",exceptions:"Exceções operacionais",lowStock:"Abaixo do ponto de reposição",expiring:"Próximo do vencimento",negative:"Saldos negativos",warehouses:"Distribuição de armazéns",statuses:"Status do estoque",recent:"Movimentos recentes",empty:"Ainda não há movimentos.",loadError:"Não foi possível carregar o resumo."},
nl:{eyebrow:"Voorraad 360",title:"Voorraadcontrolecentrum",description:"Beheer aantallen, waarde, beschikbaarheid, magazijnverdeling en kritieke uitzonderingen op één plek.",refreshed:"Laatst berekend",retry:"Opnieuw proberen",physical:"Fysieke voorraad",available:"Beschikbaar",reserved:"Gereserveerd",value:"Voorraadwaarde",products:"Voorraadartikelen",dimensions:"Voorraaddimensies",exceptions:"Operationele uitzonderingen",lowStock:"Onder bestelpunt",expiring:"Binnenkort vervallen",negative:"Negatieve saldi",warehouses:"Magazijnverdeling",statuses:"Voorraadstatussen",recent:"Recente mutaties",empty:"Nog geen voorraadmutaties.",loadError:"Voorraadoverzicht kon niet worden geladen."},
pl:{eyebrow:"Zapasy 360",title:"Centrum kontroli zapasów",description:"Zarządzaj ilością, wartością, dostępnością, rozkładem magazynowym i krytycznymi wyjątkami w jednym miejscu.",refreshed:"Ostatnie obliczenie",retry:"Spróbuj ponownie",physical:"Stan fizyczny",available:"Dostępne",reserved:"Zarezerwowane",value:"Wartość zapasów",products:"Produkty magazynowe",dimensions:"Wymiary zapasu",exceptions:"Wyjątki operacyjne",lowStock:"Poniżej punktu zamówienia",expiring:"Bliski termin ważności",negative:"Ujemne salda",warehouses:"Rozkład magazynów",statuses:"Statusy zapasu",recent:"Ostatnie ruchy",empty:"Brak ruchów magazynowych.",loadError:"Nie udało się wczytać podsumowania."},
ru:{eyebrow:"Запасы 360",title:"Центр управления запасами",description:"Контролируйте количество, стоимость, доступность, распределение и критические исключения в одном месте.",refreshed:"Последний расчет",retry:"Повторить",physical:"Физический запас",available:"Доступно",reserved:"Зарезервировано",value:"Стоимость запасов",products:"Товары в запасе",dimensions:"Измерения запасов",exceptions:"Операционные исключения",lowStock:"Ниже точки заказа",expiring:"Скоро истекает",negative:"Отрицательные остатки",warehouses:"Распределение по складам",statuses:"Статусы запасов",recent:"Последние движения",empty:"Движений пока нет.",loadError:"Не удалось загрузить обзор."},
ar:{eyebrow:"المخزون 360",title:"مركز مراقبة المخزون",description:"إدارة الكمية والقيمة والتوفر وتوزيع المستودعات والاستثناءات الحرجة من مكان واحد.",refreshed:"آخر احتساب",retry:"إعادة المحاولة",physical:"المخزون الفعلي",available:"المتاح",reserved:"المحجوز",value:"قيمة المخزون",products:"المنتجات المخزنة",dimensions:"أبعاد المخزون",exceptions:"الاستثناءات التشغيلية",lowStock:"أقل من نقطة إعادة الطلب",expiring:"قريب الانتهاء",negative:"أرصدة سالبة",warehouses:"توزيع المستودعات",statuses:"حالات المخزون",recent:"أحدث حركات المخزون",empty:"لا توجد حركات مخزون بعد.",loadError:"تعذر تحميل ملخص المخزون."},
fa:{eyebrow:"موجودی ۳۶۰",title:"مرکز کنترل موجودی",description:"مقدار، ارزش، دسترس‌پذیری، توزیع انبار و استثناهای مهم را یکجا مدیریت کنید.",refreshed:"آخرین محاسبه",retry:"تلاش دوباره",physical:"موجودی فیزیکی",available:"قابل دسترس",reserved:"رزرو شده",value:"ارزش موجودی",products:"کالاهای موجود",dimensions:"ابعاد موجودی",exceptions:"استثناهای عملیاتی",lowStock:"زیر نقطه سفارش",expiring:"نزدیک انقضا",negative:"مانده منفی",warehouses:"توزیع انبار",statuses:"وضعیت‌های موجودی",recent:"آخرین گردش‌ها",empty:"هنوز گردش موجودی وجود ندارد.",loadError:"خلاصه موجودی بارگذاری نشد."},
ja:{eyebrow:"在庫 360",title:"在庫コントロールセンター",description:"数量、金額、可用性、倉庫配分、重要な例外を一か所で管理します。",refreshed:"最終計算",retry:"再試行",physical:"実在庫",available:"利用可能",reserved:"引当済",value:"在庫金額",products:"在庫品目",dimensions:"在庫ディメンション",exceptions:"業務例外",lowStock:"発注点以下",expiring:"期限間近",negative:"マイナス在庫",warehouses:"倉庫別配分",statuses:"在庫ステータス",recent:"最近の在庫移動",empty:"在庫移動はまだありません。",loadError:"在庫概要を読み込めませんでした。"},
ko:{eyebrow:"재고 360",title:"재고 관리 센터",description:"수량, 가치, 가용성, 창고 분포와 주요 예외를 한곳에서 관리합니다.",refreshed:"마지막 계산",retry:"다시 시도",physical:"실물 재고",available:"가용 재고",reserved:"예약 재고",value:"재고 가치",products:"재고 품목",dimensions:"재고 차원",exceptions:"운영 예외",lowStock:"재주문점 미만",expiring:"유효기간 임박",negative:"음수 재고",warehouses:"창고 분포",statuses:"재고 상태",recent:"최근 재고 이동",empty:"아직 재고 이동이 없습니다.",loadError:"재고 요약을 불러오지 못했습니다."},
zh:{eyebrow:"库存 360",title:"库存控制中心",description:"在一个页面管理数量、价值、可用量、仓库分布和关键异常。",refreshed:"最后计算",retry:"重试",physical:"实际库存",available:"可用库存",reserved:"已预留",value:"库存价值",products:"库存产品",dimensions:"库存维度",exceptions:"运营异常",lowStock:"低于再订货点",expiring:"即将到期",negative:"负库存",warehouses:"仓库分布",statuses:"库存状态",recent:"最近库存移动",empty:"暂无库存移动。",loadError:"无法加载库存概览。"}}

type DashboardData={summary:{physicalQuantity:number;reservedQuantity:number;availableQuantity:number;inventoryValue:number;productCount:number;warehouseCount:number;balanceDimensionCount:number;negativeBalanceCount:number;lowStockProductCount:number;expiringLotCount:number};warehouses:Array<{warehouseId:number;warehouseCode:string;warehouseName:string;physicalQuantity:number;availableQuantity:number;inventoryValue:number}>;statuses:Array<{statusCode:string;statusName:string;physicalQuantity:number;availableQuantity:number;inventoryValue:number}>;recentMovements:Array<{id:number;documentType:string;documentNumber:string;postingDate:string;movementType:string;productCode:string;productName:string;warehouseCode:string;quantity:number;totalCost:number}>;generatedAtUtc:string};
type Envelope<T>={data:T};

export function InventoryDashboardPage():ReactElement{
 const{i18n,t}=useTranslation("erp");const language=(i18n.resolvedLanguage||i18n.language||"en").split("-")[0];const c=copy[language]??copy.en;const branchId=useAuthStore(s=>s.branch?.id);const numericBranchId=branchId&&Number.isFinite(Number(branchId))?Number(branchId):undefined;
 const query=useQuery({queryKey:["inventory-dashboard",numericBranchId],queryFn:()=>api.get<Envelope<DashboardData>>("/api/inventory/dashboard",{params:{branchId:numericBranchId,expiryWarningDays:60}}),refetchInterval:60000});const data=query.data?.data;const maxWarehouseValue=useMemo(()=>Math.max(1,...(data?.warehouses.map(x=>Math.abs(x.inventoryValue))??[])),[data]);
 const metrics=data?[{label:c.physical,value:formatSystemAmount(data.summary.physicalQuantity),icon:Boxes,tone:"text-cyan-600 bg-cyan-500/10"},{label:c.available,value:formatSystemAmount(data.summary.availableQuantity),icon:PackageCheck,tone:"text-emerald-600 bg-emerald-500/10"},{label:c.reserved,value:formatSystemAmount(data.summary.reservedQuantity),icon:ShieldCheck,tone:"text-violet-600 bg-violet-500/10"},{label:c.value,value:formatSystemCurrency(data.summary.inventoryValue),icon:Warehouse,tone:"text-amber-600 bg-amber-500/10"}]:[];
 return <div className="space-y-5 pb-8"><section className="metivon-hero relative overflow-hidden rounded-3xl p-6 md:p-8"><div className="relative flex flex-col justify-between gap-5 lg:flex-row lg:items-end"><div><p className="text-xs font-semibold uppercase tracking-[.24em] text-white/65">{c.eyebrow}</p><h1 className="mt-2 text-3xl font-semibold md:text-4xl">{c.title}</h1><p className="mt-2 max-w-3xl text-white/75">{c.description}</p></div><div className="flex flex-wrap gap-2"><Button asChild variant="secondary"><Link to="/inventory/balances">{t("nav.balances")}<ArrowRight className="h-4 w-4"/></Link></Button><Button asChild className="bg-white text-slate-900 hover:bg-white/90"><Link to="/inventory/transactions">{t("nav.movements")}<ArrowRight className="h-4 w-4"/></Link></Button></div></div></section>
 {query.isError?<section className="rounded-3xl border border-rose-200 bg-rose-50 p-8 text-center dark:border-rose-900/50 dark:bg-rose-950/20"><AlertTriangle className="mx-auto h-9 w-9 text-rose-500"/><p className="mt-3 font-semibold">{c.loadError}</p><Button className="mt-4" variant="outline" onClick={()=>void query.refetch()}><RefreshCw className="h-4 w-4"/>{c.retry}</Button></section>:null}
 {data?<><section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{metrics.map(({label,value,icon:Icon,tone})=><article key={label} className="rounded-2xl border bg-card p-5 shadow-sm"><div className={`inline-flex rounded-xl p-2.5 ${tone}`}><Icon className="h-5 w-5"/></div><p className="mt-4 text-xs font-semibold uppercase tracking-wider text-muted-foreground">{label}</p><p className="mt-1 text-2xl font-bold tracking-tight">{value}</p></article>)}</section>
 <section className="grid gap-4 lg:grid-cols-[1.35fr_.65fr]"><article className="rounded-3xl border bg-card p-5"><div className="flex items-center justify-between"><div><h2 className="font-semibold">{c.warehouses}</h2><p className="text-xs text-muted-foreground">{data.summary.warehouseCount} · {c.warehouses.toLocaleLowerCase()}</p></div><Warehouse className="h-5 w-5 text-emerald-500"/></div><div className="mt-5 space-y-4">{data.warehouses.map(x=><div key={x.warehouseId}><div className="mb-1.5 flex items-center justify-between gap-3 text-sm"><span className="truncate font-medium">{x.warehouseCode} · {x.warehouseName}</span><span className="font-mono text-xs">{formatSystemCurrency(x.inventoryValue)}</span></div><div className="h-2 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full bg-gradient-to-r from-emerald-500 to-cyan-500" style={{width:`${Math.max(3,Math.abs(x.inventoryValue)/maxWarehouseValue*100)}%`}}/></div><div className="mt-1 flex justify-between text-[11px] text-muted-foreground"><span>{c.physical}: {formatSystemAmount(x.physicalQuantity)}</span><span>{c.available}: {formatSystemAmount(x.availableQuantity)}</span></div></div>)}</div></article>
 <article className="rounded-3xl border bg-card p-5"><h2 className="font-semibold">{c.exceptions}</h2><div className="mt-4 space-y-3">{[{label:c.lowStock,value:data.summary.lowStockProductCount,icon:AlertTriangle,color:"text-amber-600 bg-amber-500/10"},{label:c.expiring,value:data.summary.expiringLotCount,icon:CalendarClock,color:"text-rose-600 bg-rose-500/10"},{label:c.negative,value:data.summary.negativeBalanceCount,icon:Boxes,color:"text-violet-600 bg-violet-500/10"}].map(({label,value,icon:Icon,color})=><div key={label} className="flex items-center justify-between rounded-2xl border p-3"><div className="flex items-center gap-3"><span className={`rounded-xl p-2 ${color}`}><Icon className="h-4 w-4"/></span><span className="text-sm font-medium">{label}</span></div><span className="text-xl font-bold">{value}</span></div>)}</div><div className="mt-4 grid grid-cols-2 gap-2 text-center"><div className="rounded-xl bg-muted/60 p-3"><p className="text-xl font-bold">{data.summary.productCount}</p><p className="text-[11px] text-muted-foreground">{c.products}</p></div><div className="rounded-xl bg-muted/60 p-3"><p className="text-xl font-bold">{data.summary.balanceDimensionCount}</p><p className="text-[11px] text-muted-foreground">{c.dimensions}</p></div></div></article></section>
 <section className="grid gap-4 xl:grid-cols-[.7fr_1.3fr]"><article className="rounded-3xl border bg-card p-5"><h2 className="font-semibold">{c.statuses}</h2><div className="mt-4 space-y-2">{data.statuses.map(x=><div key={x.statusCode} className="flex items-center justify-between rounded-xl bg-muted/50 px-3 py-2.5"><div><p className="text-sm font-medium">{x.statusName}</p><p className="text-[11px] text-muted-foreground">{x.statusCode}</p></div><div className="text-right"><p className="font-mono text-sm font-semibold">{formatSystemAmount(x.physicalQuantity)}</p><p className="text-[11px] text-muted-foreground">{formatSystemCurrency(x.inventoryValue)}</p></div></div>)}</div></article><article className="overflow-hidden rounded-3xl border bg-card"><div className="flex items-center justify-between border-b p-5"><div><h2 className="font-semibold">{c.recent}</h2><p className="text-xs text-muted-foreground">{c.refreshed}: {formatSystemDateTime(data.generatedAtUtc)}</p></div><History className="h-5 w-5 text-cyan-500"/></div><div className="divide-y">{data.recentMovements.length?data.recentMovements.map(x=><div key={x.id} className="grid gap-2 p-4 text-sm sm:grid-cols-[1fr_auto] sm:items-center"><div className="min-w-0"><p className="truncate font-medium">{x.productCode} · {x.productName}</p><p className="mt-1 truncate text-xs text-muted-foreground">{x.documentType} · {x.documentNumber} · {x.warehouseCode} · {formatSystemDateTime(x.postingDate)}</p></div><div className="text-left sm:text-right"><p className={`font-mono font-semibold ${x.quantity<0?"text-rose-600":"text-emerald-600"}`}>{x.quantity>0?"+":""}{formatSystemAmount(x.quantity)}</p><p className="text-[11px] text-muted-foreground">{t(`statuses.${x.movementType}`,{defaultValue:x.movementType})}</p></div></div>):<p className="p-8 text-center text-sm text-muted-foreground">{c.empty}</p>}</div></article></section></>:query.isLoading?<section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{Array.from({length:4}).map((_,i)=><div key={i} className="h-32 animate-pulse rounded-2xl bg-muted"/>)}</section>:null}</div>;
}
